//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WcfReget.WsSupplier {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WsSupplierSoap", Namespace="http://tempuri.org/")]
    public partial class WsSupplier : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ImportSuppliersFromExcelOperationCompleted;
        
        private System.Threading.SendOrPostCallback ImportSuppliersFromBaanFileOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WsSupplier() {
            this.Url = global::WcfReget.Properties.Settings.Default.WcfReget_WsSupplier_WsSupplier;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ImportSuppliersFromExcelCompletedEventHandler ImportSuppliersFromExcelCompleted;
        
        /// <remarks/>
        public event ImportSuppliersFromBaanFileCompletedEventHandler ImportSuppliersFromBaanFileCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ImportSuppliersFromExcel", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ImportSuppliersFromExcel(int supplierGroupId) {
            this.Invoke("ImportSuppliersFromExcel", new object[] {
                        supplierGroupId});
        }
        
        /// <remarks/>
        public void ImportSuppliersFromExcelAsync(int supplierGroupId) {
            this.ImportSuppliersFromExcelAsync(supplierGroupId, null);
        }
        
        /// <remarks/>
        public void ImportSuppliersFromExcelAsync(int supplierGroupId, object userState) {
            if ((this.ImportSuppliersFromExcelOperationCompleted == null)) {
                this.ImportSuppliersFromExcelOperationCompleted = new System.Threading.SendOrPostCallback(this.OnImportSuppliersFromExcelOperationCompleted);
            }
            this.InvokeAsync("ImportSuppliersFromExcel", new object[] {
                        supplierGroupId}, this.ImportSuppliersFromExcelOperationCompleted, userState);
        }
        
        private void OnImportSuppliersFromExcelOperationCompleted(object arg) {
            if ((this.ImportSuppliersFromExcelCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ImportSuppliersFromExcelCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ImportSuppliersFromBaanFile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ImportSuppliersFromBaanFile(int supplierGroupId) {
            this.Invoke("ImportSuppliersFromBaanFile", new object[] {
                        supplierGroupId});
        }
        
        /// <remarks/>
        public void ImportSuppliersFromBaanFileAsync(int supplierGroupId) {
            this.ImportSuppliersFromBaanFileAsync(supplierGroupId, null);
        }
        
        /// <remarks/>
        public void ImportSuppliersFromBaanFileAsync(int supplierGroupId, object userState) {
            if ((this.ImportSuppliersFromBaanFileOperationCompleted == null)) {
                this.ImportSuppliersFromBaanFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnImportSuppliersFromBaanFileOperationCompleted);
            }
            this.InvokeAsync("ImportSuppliersFromBaanFile", new object[] {
                        supplierGroupId}, this.ImportSuppliersFromBaanFileOperationCompleted, userState);
        }
        
        private void OnImportSuppliersFromBaanFileOperationCompleted(object arg) {
            if ((this.ImportSuppliersFromBaanFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ImportSuppliersFromBaanFileCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void ImportSuppliersFromExcelCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void ImportSuppliersFromBaanFileCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591