//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kamsyk.Reget.PdfGenerator.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PdfGeneratorResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PdfGeneratorResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kamsyk.Reget.PdfGenerator.Resources.PdfGeneratorResource", typeof(PdfGeneratorResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepting this means accepting purchase order Terms and Conditions included in this purchase order, including any annex. (Ex. Drawings, special requirements, specifications, contractual terms) if any.
        /// </summary>
        internal static string AcceptBg {
            get {
                return ResourceManager.GetString("AcceptBg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Connection.
        /// </summary>
        internal static string BankConnection {
            get {
                return ResourceManager.GetString("BankConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This order number must appear on bills or any other documents related to the order..
        /// </summary>
        internal static string BgOrderNrInfo {
            get {
                return ResourceManager.GetString("BgOrderNrInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Invoice.
        /// </summary>
        internal static string ByInvoice {
            get {
                return ResourceManager.GetString("ByInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, be so kind and confirm obtaining of this order within 5 days as the latest. If you fail to reply by then we will consider this orders as confirmed..
        /// </summary>
        internal static string ConfirmInfo {
            get {
                return ResourceManager.GetString("ConfirmInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person.
        /// </summary>
        internal static string ContactPerson {
            get {
                return ResourceManager.GetString("ContactPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Nr..
        /// </summary>
        internal static string ContractNr {
            get {
                return ResourceManager.GetString("ContractNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string DateFrom {
            get {
                return ResourceManager.GetString("DateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deliver to.
        /// </summary>
        internal static string DeliverTo {
            get {
                return ResourceManager.GetString("DeliverTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Date.
        /// </summary>
        internal static string DeliveryDate {
            get {
                return ResourceManager.GetString("DeliveryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descriptions.
        /// </summary>
        internal static string Descriptions {
            get {
                return ResourceManager.GetString("Descriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send electronic invoices to {0}..
        /// </summary>
        internal static string EInvoiceInfo {
            get {
                return ResourceManager.GetString("EInvoiceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated.
        /// </summary>
        internal static string Generated {
            get {
                return ResourceManager.GetString("Generated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important.
        /// </summary>
        internal static string Important {
            get {
                return ResourceManager.GetString("Important", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An integral part of the order is the General Purchase Terms..
        /// </summary>
        internal static string IntegralPart {
            get {
                return ResourceManager.GetString("IntegralPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An integral part of the order are the General Purchase Terms and &lt;a href=https://www.utc.com/-/media/project/united-technologies/utc/files/code-of-conduct/english.pdf?rev=2040272be4514dc8ae1a9d6a3f922c5a&gt;Supplier Code of Conduct&lt;/a&gt;.
        /// </summary>
        internal static string IntegralPartBV {
            get {
                return ResourceManager.GetString("IntegralPartBV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead Time.
        /// </summary>
        internal static string LeadTime {
            get {
                return ResourceManager.GetString("LeadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        internal static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        internal static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Confirmation.
        /// </summary>
        internal static string OrderConfirmation {
            get {
                return ResourceManager.GetString("OrderConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Date.
        /// </summary>
        internal static string OrderDate {
            get {
                return ResourceManager.GetString("OrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are ordering.
        /// </summary>
        internal static string OrderDetails {
            get {
                return ResourceManager.GetString("OrderDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordered By.
        /// </summary>
        internal static string OrderedBy {
            get {
                return ResourceManager.GetString("OrderedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orderer.
        /// </summary>
        internal static string Orderer {
            get {
                return ResourceManager.GetString("Orderer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Number.
        /// </summary>
        internal static string OrderNr {
            get {
                return ResourceManager.GetString("OrderNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use our order number as a reference number on each documents and correspondence..
        /// </summary>
        internal static string OrderNrInfo {
            get {
                return ResourceManager.GetString("OrderNrInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use our order number as a reference number on each documents and correspondence. Invoice without the reference of order number will be not paid! INVOICE HAS TO BE AVAILABLE WITH THE DELIVERY..
        /// </summary>
        internal static string OrderNrInfoZona {
            get {
                return ResourceManager.GetString("OrderNrInfoZona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person.
        /// </summary>
        internal static string OurResponsiblePerson {
            get {
                return ResourceManager.GetString("OurResponsiblePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        internal static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Nr..
        /// </summary>
        internal static string PhoneNr {
            get {
                return ResourceManager.GetString("PhoneNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Per Unit (wo VAT).
        /// </summary>
        internal static string PricePerUnit {
            get {
                return ResourceManager.GetString("PricePerUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Order.
        /// </summary>
        internal static string PurchaseOrder {
            get {
                return ResourceManager.GetString("PurchaseOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Order No..
        /// </summary>
        internal static string PurchaseOrderNr {
            get {
                return ResourceManager.GetString("PurchaseOrderNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        internal static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Invoice To.
        /// </summary>
        internal static string SendInvoiceTo {
            get {
                return ResourceManager.GetString("SendInvoiceTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature and Stamp Buyer.
        /// </summary>
        internal static string SignatureBuyer {
            get {
                return ResourceManager.GetString("SignatureBuyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature and Stamp Customer (Order Acceptance).
        /// </summary>
        internal static string SignatureCustomer {
            get {
                return ResourceManager.GetString("SignatureCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Instructions.
        /// </summary>
        internal static string SpecialInstructions {
            get {
                return ResourceManager.GetString("SpecialInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sr. No..
        /// </summary>
        internal static string SrNr {
            get {
                return ResourceManager.GetString("SrNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        internal static string Supplier {
            get {
                return ResourceManager.GetString("Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string SupplierId {
            get {
                return ResourceManager.GetString("SupplierId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of Payment.
        /// </summary>
        internal static string TermsOfPayment {
            get {
                return ResourceManager.GetString("TermsOfPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Price.
        /// </summary>
        internal static string TotalPrice {
            get {
                return ResourceManager.GetString("TotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Value (wo VAT).
        /// </summary>
        internal static string TotalValue {
            get {
                return ResourceManager.GetString("TotalValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vat Id.
        /// </summary>
        internal static string VatId {
            get {
                return ResourceManager.GetString("VatId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Contact.
        /// </summary>
        internal static string VendorContact {
            get {
                return ResourceManager.GetString("VendorContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Quote.
        /// </summary>
        internal static string YourQuote {
            get {
                return ResourceManager.GetString("YourQuote", resourceCulture);
            }
        }
    }
}
