//*************************************************************************************
//* This classes were generated by RegetDdGenerator.sql script                          *
//*************************************************************************************
using System;

namespace Kamsyk.Reget.Model.DataDictionary {
    #region RequestMultiOrderer
    public class RequestMultiOrdererData {

        #region Constants
        public const string TABLE_NAME = "REQUEST_MULTI_ORDERER";
        public const string REQUEST_EVENT_ID_FIELD = "request_event_id";
        public const string REQUEST_VERSION_FIELD = "request_version";
        public const string ORDERER_ID_FIELD = "orderer_id";

        #endregion
    }
    #endregion

    #region UserGridsetting
    public class UserGridsettingData {

        #region Constants
        public const string TABLE_NAME = "USER_GRIDSETTING";
        public const string USER_ID_FIELD = "user_id";
        public const string GRID_NAME_FIELD = "grid_name";
        public const string GRID_PAGE_SIZE_FIELD = "grid_page_size";
        public const string FILTER_FIELD = "filter";
        public const string SORT_FIELD = "sort";
        public const string COLUMNS_FIELD = "columns";

        public const int GRID_NAME_LENGTH = 150;
        public const int FILTER_LENGTH = 500;
        public const int SORT_LENGTH = 500;
        public const int COLUMNS_LENGTH = 500;
        #endregion
    }
    #endregion

    #region ApproveLevel
    public class ApproveLevelData {

        #region Constants
        public const string TABLE_NAME = "APPROVE_LEVEL";
        public const string ID_FIELD = "id";
        public const string APPROVE_LEVEL_FIELD = "approve_level";
        public const string NAME_FIELD = "name";
        public const string ACTIVE_FIELD = "active";

        public const int NAME_LENGTH = 50;
        #endregion
    }
    #endregion

    #region Sysdiagrams
    public class SysdiagramsData {

        #region Constants
        public const string TABLE_NAME = "SYSDIAGRAMS";
        public const string NAME_FIELD = "name";
        public const string PRINCIPAL_ID_FIELD = "principal_id";
        public const string DIAGRAM_ID_FIELD = "diagram_id";
        public const string VERSION_FIELD = "version";
        public const string DEFINITION_FIELD = "definition";

        public const int NAME_LENGTH = 128;
        #endregion
    }
    #endregion

    #region BusinesstripCentreGroup
    public class BusinesstripCentreGroupData {

        #region Constants
        public const string TABLE_NAME = "BUSINESSTRIP_CENTRE_GROUP";
        public const string ID_FIELD = "id";
        public const string NAME_FIELD = "name";
        public const string CURRENCY_ID_FIELD = "currency_id";
        public const string COMPANY_ID_FIELD = "company_id";
        public const string ACTIVE_FIELD = "active";

        public const int NAME_LENGTH = 50;
        #endregion
    }
    #endregion

    #region RequestAuthorizedusers
    public class RequestAuthorizedusersData {

        #region Constants
        public const string TABLE_NAME = "REQUEST_AUTHORIZEDUSERS";
        public const string REQUEST_ID_FIELD = "request_id";
        public const string REQUEST_VERSION_FIELD = "request_version";
        public const string USER_ID_FIELD = "user_id";
        public const string IS_LAST_VERSION_FIELD = "is_last_version";

        #endregion
    }
    #endregion

    #region CompanyCurrency
    public class CompanyCurrencyData {

        #region Constants
        public const string TABLE_NAME = "COMPANY_CURRENCY";
        public const string COMPANY_ID_FIELD = "company_id";
        public const string CURRENCY_ID_FIELD = "currency_id";

        #endregion
    }
    #endregion

    #region PurchasegroupOrderer
    public class PurchasegroupOrdererData {

        #region Constants
        public const string TABLE_NAME = "PURCHASEGROUP_ORDERER";
        public const string PURCHASE_GROUP_ID_FIELD = "purchase_group_id";
        public const string ORDERER_ID_FIELD = "orderer_id";

        #endregion
    }
    #endregion

    #region PurchasegroupRequestor
    public class PurchasegroupRequestorData {

        #region Constants
        public const string TABLE_NAME = "PURCHASEGROUP_REQUESTOR";
        public const string PURCHASE_GROUP_ID_FIELD = "purchase_group_id";
        public const string CENTRE_ID_FIELD = "centre_id";
        public const string REQUESTOR_ID_FIELD = "requestor_id";

        #endregion
    }
    #endregion

    #region ParticipantroleGlobal
    public class ParticipantroleGlobalData {

        #region Constants
        public const string TABLE_NAME = "PARTICIPANTROLE_GLOBAL";
        public const string PARTICIPANT_ID_FIELD = "participant_id";
        public const string ROLE_ID_FIELD = "role_id";

        #endregion
    }
    #endregion

    #region ParticipantroleCentregroup
    public class ParticipantroleCentregroupData {

        #region Constants
        public const string TABLE_NAME = "PARTICIPANTROLE_CENTREGROUP";
        public const string PARTICIPANT_ID_FIELD = "participant_id";
        public const string CENTRE_GROUP_ID_FIELD = "centre_group_id";
        public const string ROLE_ID_FIELD = "role_id";

        #endregion
    }
    #endregion

    #region RequestText
    public class RequestTextData {

        #region Constants
        public const string TABLE_NAME = "REQUEST_TEXT";
        public const string REQUEST_ID_FIELD = "request_id";
        public const string REQUEST_VERSION_FIELD = "request_version";
        public const string APP_TEXT_STORE_ID_FIELD = "app_text_store_id";
        public const string MODIFY_DATE_FIELD = "modify_date";
        public const string IS_LAST_VERSION_FIELD = "is_last_version";

        #endregion
    }
    #endregion

    #region RequestMail
    public class RequestMailData {

        #region Constants
        public const string TABLE_NAME = "REQUEST_MAIL";
        public const string ID_FIELD = "id";
        public const string REQUEST_ID_FIELD = "request_id";
        public const string REQUEST_VERSION_FIELD = "request_version";
        public const string SENDER_FIELD = "sender";
        public const string RECIPIENTS_FIELD = "recipients";
        public const string ORDER_NAME_FIELD = "order_name";
        public const string ORDER_CONTENT_FIELD = "order_content";
        public const string ATTACHMENT_IDS_FIELD = "attachment_ids";
        public const string TERM_COND_NAME_FIELD = "term_cond_name";
        public const string TERM_COND_CONTENT_FIELD = "term_cond_content";
        public const string SENT_DATE_FIELD = "sent_date";

        public const int SENDER_LENGTH = 150;
        public const int RECIPIENTS_LENGTH = 500;
        public const int ORDER_NAME_LENGTH = 50;
        public const int ATTACHMENT_IDS_LENGTH = 500;
        public const int TERM_COND_NAME_LENGTH = 150;
        #endregion
    }
    #endregion

    #region CustomfieldCompany
    public class CustomfieldCompanyData {

        #region Constants
        public const string TABLE_NAME = "CUSTOMFIELD_COMPANY";
        public const string CUSTOM_FIELD_ID_FIELD = "custom_field_id";
        public const string COMPANY_ID_FIELD = "company_id";

        #endregion
    }
    #endregion

    #region RequestEvent
    public class RequestEventData {

        #region Constants
        public const string TABLE_NAME = "REQUEST_EVENT";
        public const string ID_FIELD = "id";
        public const string VERSION_FIELD = "version";
        public const string REQUEST_NR_FIELD = "request_nr";
        public const string REQUESTOR_FIELD = "requestor";
        public const string MANAGER1_FIELD = "manager1";
        public const string MANAGER2_FIELD = "manager2";
        public const string MANAGER3_FIELD = "manager3";
        public const string MANAGER4_FIELD = "manager4";
        public const string MANAGER5_FIELD = "manager5";
        public const string ISSUED_FIELD = "issued";
        public const string REQUEST_TEXT_FIELD = "request_text";
        public const string LEAD_TIME_FIELD = "lead_time";
        public const string ESTIMATED_PRICE_FIELD = "estimated_price";
        public const string SUPPLIER_FIELD = "supplier";
        public const string REMARKS_FIELD = "remarks";
        public const string PURCH_MAT_INCLUDED_FIELD = "purch_mat_included";
        public const string APPROVED_1_FIELD = "approved_1";
        public const string APPROVED_2_FIELD = "approved_2";
        public const string APPROVED_3_FIELD = "approved_3";
        public const string APPROVED_4_FIELD = "approved_4";
        public const string APPROVED_5_FIELD = "approved_5";
        public const string ORDERED_FIELD = "ordered";
        public const string DELIVERED_FIELD = "delivered";
        public const string REQUEST_STATUS_FIELD = "request_status";
        public const string CURRENCY_ID_FIELD = "currency_id";
        public const string CENTRE_GROUP_ID_FIELD = "centre_group_id";
        public const string COUNTRY_ID_FIELD = "country_id";
        public const string SUPPLIER_ID_FIELD = "supplier_id";
        public const string USE_SUPPLIER_LIST_FIELD = "use_supplier_list";
        public const string MANAGER1REMARK_FIELD = "manager1Remark";
        public const string MANAGER2REMARK_FIELD = "manager2Remark";
        public const string MANAGER3REMARK_FIELD = "manager3Remark";
        public const string MANAGER4REMARK_FIELD = "manager4Remark";
        public const string MANAGER5REMARK_FIELD = "manager5Remark";
        public const string ORDERER_REMARK_FIELD = "orderer_remark";
        public const string ORDERER_ID_FIELD = "orderer_id";
        public const string SEND_BACK_REASON_FIELD = "send_back_reason";
        public const string PURCHASE_GROUP_ID_FIELD = "purchase_group_id";
        public const string ACTUAL_PRICE_FIELD = "actual_price";
        public const string ACTULA_DELIVERY_DATE_FIELD = "actula_delivery_date";
        public const string INVOICE_NUMBER_FIELD = "invoice_number";
        public const string ACT_CURRENCY_ID_FIELD = "act_currency_id";
        public const string EXCHANGE_RATE_FIELD = "exchange_rate";
        public const string SHIP_TO_ADDRESS_COMPANY_NAME_FIELD = "ship_to_address_company_name";
        public const string SHIP_TO_ADDRESS_STREET_FIELD = "ship_to_address_street";
        public const string SHIP_TO_ADDRESS_CITY_FIELD = "ship_to_address_city";
        public const string SHIP_TO_ADDRESS_ZIP_FIELD = "ship_to_address_zip";
        public const string ORDER_FILE_NAME_FIELD = "order_file_name";
        public const string REQUEST_CENTRE_ID_FIELD = "request_centre_id";
        public const string EXPORT_PRICE_TO_ORDER_FIELD = "export_price_to_order";
        public const string PROFYLAX_NR_FIELD = "profylax_nr";
        public const string YEAR_ORDER_FIELD = "year_order";
        public const string CONTRACT_NR_FIELD = "contract_nr";
        public const string UNIT_NR_FIELD = "unit_nr";
        public const string JOB_NR_FIELD = "job_nr";
        public const string COMMENTATOR_ID_FIELD = "commentator_id";
        public const string COMMENT_FIELD = "comment";
        public const string LAST_EVENT_FIELD = "last_event";
        public const string TEMPORARY_REQUEST_FIELD = "temporary_request";
        public const string MODIFY_USER_FIELD = "modify_user";
        public const string MODIFY_DATE_FIELD = "modify_date";
        public const string INTEGRATION_CODE_FIELD = "integration_code";
        public const string NOT_ORDERED_NOTIFY_DATE_FIELD = "not_ordered_notify_date";
        public const string IS_MANAGER1_INSPECTOR_FIELD = "is_manager1_inspector";
        public const string IS_MANAGER2_INSPECTOR_FIELD = "is_manager2_inspector";
        public const string IS_MANAGER3_INSPECTOR_FIELD = "is_manager3_inspector";
        public const string IS_MANAGER4_INSPECTOR_FIELD = "is_manager4_inspector";
        public const string IS_MANAGER5_INSPECTOR_FIELD = "is_manager5_inspector";
        public const string MANAGER6_FIELD = "manager6";
        public const string APPROVED_6_FIELD = "approved_6";
        public const string MANAGER6REMARK_FIELD = "manager6Remark";
        public const string IS_MANAGER6_INSPECTOR_FIELD = "is_manager6_inspector";
        public const string CAR_NR_FIELD = "car_nr";
        public const string IS_OUT_OF_EU_FIELD = "is_out_of_eu";
        public const string IS_ORDER_NEEDED_FIELD = "is_order_needed";
        public const string PRIVACY_ID_FIELD = "privacy_id";

        public const int REQUEST_NR_LENGTH = 50;
        public const int INVOICE_NUMBER_LENGTH = 50;
        public const int SHIP_TO_ADDRESS_COMPANY_NAME_LENGTH = 50;
        public const int SHIP_TO_ADDRESS_STREET_LENGTH = 150;
        public const int SHIP_TO_ADDRESS_CITY_LENGTH = 50;
        public const int SHIP_TO_ADDRESS_ZIP_LENGTH = 20;
        public const int ORDER_FILE_NAME_LENGTH = 50;
        public const int PROFYLAX_NR_LENGTH = 50;
        public const int CONTRACT_NR_LENGTH = 50;
        public const int UNIT_NR_LENGTH = 50;
        public const int JOB_NR_LENGTH = 50;
        public const int INTEGRATION_CODE_LENGTH = 10;
        public const int CAR_NR_LENGTH = 50;
        #endregion
    }
    #endregion

    #region CustomfieldLocal
    public class CustomfieldLocalData {

        #region Constants
        public const string TABLE_NAME = "CUSTOMFIELD_LOCAL";
        public const string CUSTOM_FIELD_ID_FIELD = "custom_field_id";
        public const string CULTURE_FIELD = "culture";
        public const string LOCAL_TEXT_FIELD = "local_text";

        public const int CULTURE_LENGTH = 50;
        public const int LOCAL_TEXT_LENGTH = 50;
        #endregion
    }
    #endregion

    #region CustomField
    public class CustomFieldData {

        #region Constants
        public const string TABLE_NAME = "CUSTOM_FIELD";
        public const string ID_FIELD = "id";
        public const string LABEL_FIELD = "label";
        public const string IS_MANDATORY_FIELD = "is_mandatory";
        public const string DATE_TYPE_ID_FIELD = "date_type_id";
        public const string IS_ACTIVE_FIELD = "is_active";

        public const int LABEL_LENGTH = 50;
        #endregion
    }
    #endregion

    #region UnitMeasurement
    public class UnitMeasurementData {

        #region Constants
        public const string TABLE_NAME = "UNIT_MEASUREMENT";
        public const string ID_FIELD = "id";
        public const string NAME_FIELD = "name";
        public const string CODE_FIELD = "code";
        public const string UNIT_VALUE_TYPE_ID_FIELD = "unit_value_type_id";
        public const string ACTIVE_FIELD = "active";

        public const int NAME_LENGTH = 50;
        public const int CODE_LENGTH = 5;
        #endregion
    }
    #endregion

    #region MaintenanceEventCode
    public class MaintenanceEventCodeData {

        #region Constants
        public const string TABLE_NAME = "MAINTENANCE_EVENT_CODE";
        public const string ID_FIELD = "id";
        public const string DESCRIPTION_FIELD = "description";

        public const int DESCRIPTION_LENGTH = 150;
        #endregion
    }
    #endregion

    #region RequesteventCustomfieldvalue
    public class RequesteventCustomfieldvalueData {

        #region Constants
        public const string TABLE_NAME = "REQUESTEVENT_CUSTOMFIELDVALUE";
        public const string REQUEST_EVENT_ID_FIELD = "request_event_id";
        public const string REQUEST_EVENT_VERSION_FIELD = "request_event_version";
        public const string CUSTOM_FIELD_ID_FIELD = "custom_field_id";
        public const string STRING_VALUE_FIELD = "string_value";
        public const string IS_ACTIVE_FIELD = "is_active";

        public const int STRING_VALUE_LENGTH = 50;
        #endregion
    }
    #endregion

    #region Participantphoto
    public class ParticipantphotoData {

        #region Constants
        public const string TABLE_NAME = "PARTICIPANTPHOTO";
        public const string PARTICIPANT_ID_FIELD = "participant_id";
        public const string USER_PICTURE_240_FIELD = "user_picture_240";
        public const string MODIF_DATE_FIELD = "modif_date";

        #endregion
    }
    #endregion

    #region AssetRequestIdentificator
    public class AssetRequestIdentificatorData {

        #region Constants
        public const string TABLE_NAME = "ASSET_REQUEST_IDENTIFICATOR";
        public const string REQUEST_TYPE_FIELD = "request_type";
        public const string REQUEST_YEAR_FIELD = "request_year";
        public const string LAST_REQUEST_ID_FIELD = "last_request_id";

        public const int REQUEST_TYPE_LENGTH = 10;
        #endregion
    }
    #endregion

    #region ParticipantOfficeRole
    public class ParticipantOfficeRoleData {

        #region Constants
        public const string TABLE_NAME = "PARTICIPANT_OFFICE_ROLE";
        public const string PARTICIPANT_ID_FIELD = "participant_id";
        public const string OFFICE_ID_FIELD = "office_id";
        public const string ROLE_ID_FIELD = "role_id";

        #endregion
    }
    #endregion

    #region PurchaseGroupLimit
    public class PurchaseGroupLimitData {

        #region Constants
        public const string TABLE_NAME = "PURCHASE_GROUP_LIMIT";
        public const string LIMIT_ID_FIELD = "limit_id";
        public const string PURCHASE_GROUP_ID_FIELD = "purchase_group_id";
        public const string APPROVE_LEVEL_ID_FIELD = "approve_level_id";
        public const string LIMIT_BOTTOM_FIELD = "limit_bottom";
        public const string LIMIT_TOP_FIELD = "limit_top";
        public const string SKIP_LIMIT_FIELD = "skip_limit";
        public const string IS_LIMIT_BOTTOM_MULTIPL_FIELD = "is_limit_bottom_multipl";
        public const string IS_LIMIT_TOP_MULTIPL_FIELD = "is_limit_top_multipl";
        public const string ACTIVE_FIELD = "active";
        public const string MODIFY_USER_FIELD = "modify_user";
        public const string MODIFY_DATE_FIELD = "modify_date";

        #endregion
    }
    #endregion

    #region ShipToAddress
    public class ShipToAddressData {

        #region Constants
        public const string TABLE_NAME = "SHIP_TO_ADDRESS";
        public const string ID_FIELD = "id";
        public const string PARTICIPANT_ID_FIELD = "participant_id";
        public const string CENTRE_ID_FIELD = "centre_id";
        public const string CENTRE_GROUP_ID_FIELD = "centre_group_id";
        public const string COMPANY_NAME_FIELD = "company_name";
        public const string STREET_FIELD = "street";
        public const string CITY_FIELD = "city";
        public const string ZIP_FIELD = "zip";
        public const string INVOICE_MAIL_FIELD = "invoice_mail";
        public const string ADDRESS_ID_FIELD = "address_id";
        public const string ACTIVE_FIELD = "active";

        public const int COMPANY_NAME_LENGTH = 50;
        public const int STREET_LENGTH = 150;
        public const int CITY_LENGTH = 50;
        public const int ZIP_LENGTH = 15;
        public const int INVOICE_MAIL_LENGTH = 150;
        #endregion
    }
    #endregion

    #region CompanyParentpurchasegroup
    public class CompanyParentpurchasegroupData {

        #region Constants
        public const string TABLE_NAME = "COMPANY_PARENTPURCHASEGROUP";
        public const string COMPANY_ID_FIELD = "company_id";
        public const string PARENT_PG_ID_FIELD = "parent_pg_id";

        #endregion
    }
    #endregion

    #region AssetCentreGroup
    public class AssetCentreGroupData {

        #region Constants
        public const string TABLE_NAME = "ASSET_CENTRE_GROUP";
        public const string ID_FIELD = "id";
        public const string NAME_FIELD = "name";
        public const string CURRENCY_ID_FIELD = "currency_id";
        public const string ACTIVE_FIELD = "active";

        public const int NAME_LENGTH = 50;
        #endregion
    }
    #endregion

    #region AssetRequestorCentre
    public class AssetRequestorCentreData {

        #region Constants
        public const string TABLE_NAME = "ASSET_REQUESTOR_CENTRE";
        public const string PARTICIPANT_ID_FIELD = "participant_id";
        public const string CENTRE_ID_FIELD = "centre_id";

        #endregion
    }
    #endregion

    #region PurchasegroupCustomfield
    public class PurchasegroupCustomfieldData {

        #region Constants
        public const string TABLE_NAME = "PURCHASEGROUP_CUSTOMFIELD";
        public const string PURCHASE_GROUP_ID_FIELD = "purchase_group_id";
        public const string CUSTOM_FIELD_ID_FIELD = "custom_field_id";
        public const string POSITION_INDEX_FIELD = "position_index";
        public const string ROLE_ID_FIELD = "role_id";

        #endregion
    }
    #endregion

    #region SupplierContact
    public class SupplierContactData {

        #region Constants
        public const string TABLE_NAME = "SUPPLIER_CONTACT";
        public const string ID_FIELD = "id";
        public const string SUPPLIER_ID_FIELD = "supplier_id";
        public const string FIRST_NAME_FIELD = "first_name";
        public const string SURNAME_FIELD = "surname";
        public const string EMAIL_FIELD = "email";
        public const string PHONE_FIELD = "phone";
        public const string LAST_USED_FIELD = "last_used";
        public const string MODIFIED_USER_ID_FIELD = "modified_user_id";
        public const string MODIFIED_DATE_FIELD = "modified_date";

        public const int FIRST_NAME_LENGTH = 50;
        public const int SURNAME_LENGTH = 50;
        public const int EMAIL_LENGTH = 50;
        public const int PHONE_LENGTH = 50;
        #endregion
    }
    #endregion

    #region TransportType
    public class TransportTypeData {

        #region Constants
        public const string TABLE_NAME = "TRANSPORT_TYPE";
        public const string ID_FIELD = "id";
        public const string TRANSPORT_TYPE_FIELD = "transport_type";

        public const int TRANSPORT_TYPE_LENGTH = 50;
        #endregion
    }
    #endregion

    #region Discussion
    public class DiscussionData {

        #region Constants
        public const string TABLE_NAME = "DISCUSSION";
        public const string ID_FIELD = "id";
        public const string AUTHOR_ID_FIELD = "author_id";
        public const string APP_TEXT_STORE_ID_FIELD = "app_text_store_id";
        public const string MODIF_DATE_FIELD = "modif_date";

        #endregion
    }
    #endregion

    #region Participants
    public class ParticipantsData {

        #region Constants
        public const string TABLE_NAME = "PARTICIPANTS";
        public const string ID_FIELD = "id";
        public const string COMPANY_ID_FIELD = "company_id";
        public const string FIRST_NAME_FIELD = "first_name";
        public const string SURNAME_FIELD = "surname";
        public const string USER_NAME_FIELD = "user_name";
        public const string PERSONAL_NR_FIELD = "personal_nr";
        public const string EMAIL_FIELD = "email";
        public const string PHONE_FIELD = "phone";
        public const string FAX_FIELD = "fax";
        public const string CENTRE_ID_FIELD = "centre_id";
        public const string COUNTRY_LANG_ID_FIELD = "country_lang_id";
        public const string DATE_OF_BIRTH_FIELD = "date_of_birth";
        public const string IS_EXTERNAL_FIELD = "is_external";
        public const string IS_NON_ACTIVE_FIELD = "is_non_active";
        public const string IS_APP_ADMIN_FIELD = "is_app_admin";
        public const string USER_SEARCH_KEY_FIELD = "user_search_key";
        public const string FIRST_NAME_SEARCH_KEY_FIELD = "first_name_search_key";
        public const string SURNAME_SEARCH_KEY_FIELD = "surname_search_key";
        public const string COMPANY_GROUP_ID_FIELD = "company_group_id";
        public const string ACTIVE_FIELD = "active";

        public const int FIRST_NAME_LENGTH = 50;
        public const int SURNAME_LENGTH = 50;
        public const int USER_NAME_LENGTH = 50;
        public const int PERSONAL_NR_LENGTH = 50;
        public const int EMAIL_LENGTH = 150;
        public const int PHONE_LENGTH = 20;
        public const int FAX_LENGTH = 20;
        public const int USER_SEARCH_KEY_LENGTH = 100;
        public const int FIRST_NAME_SEARCH_KEY_LENGTH = 50;
        public const int SURNAME_SEARCH_KEY_LENGTH = 50;
        #endregion
    }
    #endregion

    #region BusinesstripRequestCost
    public class BusinesstripRequestCostData {

        #region Constants
        public const string TABLE_NAME = "BUSINESSTRIP_REQUEST_COST";
        public const string REQUEST_ID_FIELD = "request_id";
        public const string REQUEST_VERSION_FIELD = "request_version";
        public const string COST_TYPE_FIELD = "cost_type";
        public const string CURRENCY_ID_FIELD = "currency_id";
        public const string AMOUNT_FIELD = "amount";

        #endregion
    }
    #endregion

    #region BusinesstripRequestTransporttype
    public class BusinesstripRequestTransporttypeData {

        #region Constants
        public const string TABLE_NAME = "BUSINESSTRIP_REQUEST_TRANSPORTTYPE";
        public const string BUSINESS_TRIP_REQUEST_ID_FIELD = "business_trip_request_id";
        public const string BUSINESS_TRIP_REQUEST_VERSION_FIELD = "business_trip_request_version";
        public const string TRANSPORT_TYPE_ID_FIELD = "transport_type_id";

        #endregion
    }
    #endregion

    #region Country
    public class CountryData {

        #region Constants
        public const string TABLE_NAME = "COUNTRY";
        public const string ID_FIELD = "id";
        public const string NAME_FIELD = "name";
        public const string CURRENCY_ID_FIELD = "currency_id";
        public const string TERRITORY_AREA_ID_FIELD = "territory_area_id";
        public const string COUNTRY_CODE_FIELD = "country_code";
        public const string ACTIVE_FIELD = "active";

        public const int NAME_LENGTH = 50;
        public const int COUNTRY_CODE_LENGTH = 5;
        #endregion
    }
    #endregion

    #region RequestItem
    public class RequestItemData {

        #region Constants
        public const string TABLE_NAME = "REQUEST_ITEM";
        public const string ID_FIELD = "id";
        public const string REQUEST_ID_FIELD = "request_id";
        public const string REQUEST_VERSION_FIELD = "request_version";
        public const string NAME_FIELD = "name";
        public const string AMOUNT_FIELD = "amount";
        public const string UNIT_PRICE_FIELD = "unit_price";
        public const string UNIT_MEASUREMENT_ID_FIELD = "unit_measurement_id";
        public const string CURRENCY_ID_FIELD = "currency_id";
        public const string IS_LAST_VERSION_FIELD = "is_last_version";

        public const int NAME_LENGTH = 500;
        #endregion
    }
    #endregion

    #region ExchangeRate
    public class ExchangeRateData {

        #region Constants
        public const string TABLE_NAME = "EXCHANGE_RATE";
        public const string SOURCE_CURRENCY_ID_FIELD = "source_currency_id";
        public const string DESTIN_CURRENCY_ID_FIELD = "destin_currency_id";
        public const string EXCHANGE_RATE_FIELD = "exchange_rate";

        #endregion
    }
    #endregion

    #region AppTextStore
    public class AppTextStoreData {

        #region Constants
        public const string TABLE_NAME = "APP_TEXT_STORE";
        public const string ID_FIELD = "id";
        public const string TEXT_CONTENT_FIELD = "text_content";
        public const string TEXT_TYPE_FIELD = "text_type";
        public const string COMPANY_ID_FIELD = "company_id";

        public const int TEXT_CONTENT_LENGTH = 0;
        #endregion
    }
    #endregion

    #region RequestIdentificator
    public class RequestIdentificatorData {

        #region Constants
        public const string TABLE_NAME = "REQUEST_IDENTIFICATOR";
        public const string CENTRE_ID_FIELD = "centre_id";
        public const string REUEAST_YEAR_FIELD = "reueast_year";
        public const string LAST_REQUEST_ID_FIELD = "last_request_id";

        #endregion
    }
    #endregion

    #region BusinesstripAllowance
    public class BusinesstripAllowanceData {

        #region Constants
        public const string TABLE_NAME = "BUSINESSTRIP_ALLOWANCE";
        public const string COUNTRY_ID_FIELD = "country_id";
        public const string CURRENCY_ID_FIELD = "currency_id";
        public const string ALLOWANCE_AMOUNT_FIELD = "allowance_amount";

        #endregion
    }
    #endregion

    #region BusinesstripIdentificator
    public class BusinesstripIdentificatorData {

        #region Constants
        public const string TABLE_NAME = "BUSINESSTRIP_IDENTIFICATOR";
        public const string YEAR_FIELD = "year";
        public const string LAST_BT_ID_FIELD = "last_bt_id";

        #endregion
    }
    #endregion

    #region ManagerRole
    public class ManagerRoleData {

        #region Constants
        public const string TABLE_NAME = "MANAGER_ROLE";
        public const string CENTRE_GROUP_ID_FIELD = "centre_group_id";
        public const string PURCHASE_GROUP_LIMIT_ID_FIELD = "purchase_group_limit_id";
        public const string APPROVE_LEVEL_ID_FIELD = "approve_level_id";
        public const string PARTICIPANT_ID_FIELD = "participant_id";
        public const string IS_INSPECTOR_FIELD = "is_inspector";
        public const string ACTIVE_FIELD = "active";
        public const string MODIFY_USER_FIELD = "modify_user";
        public const string MODIFY_DATE_FIELD = "modify_date";

        #endregion
    }
    #endregion

    #region SuppliergroupCentregroup
    public class SuppliergroupCentregroupData {

        #region Constants
        public const string TABLE_NAME = "SUPPLIERGROUP_CENTREGROUP";
        public const string CENTRE_GROUP_ID_FIELD = "centre_group_id";
        public const string SUPPLIER_GROUP_ID_FIELD = "supplier_group_id";

        #endregion
    }
    #endregion

    #region CountryLocal
    public class CountryLocalData {

        #region Constants
        public const string TABLE_NAME = "COUNTRY_LOCAL";
        public const string COUNTRY_ID_FIELD = "country_id";
        public const string CULTURE_FIELD = "culture";
        public const string LOCALIZED_NAME_FIELD = "localized_name";

        public const int CULTURE_LENGTH = 10;
        public const int LOCALIZED_NAME_LENGTH = 50;
        #endregion
    }
    #endregion

    #region Address
    public class AddressData {

        #region Constants
        public const string TABLE_NAME = "ADDRESS";
        public const string ID_FIELD = "id";
        public const string COMPANY_ID_FIELD = "company_id";
        public const string COMPANY_NAME_FIELD = "company_name";
        public const string STREET_FIELD = "street";
        public const string CITY_FIELD = "city";
        public const string ZIP_FIELD = "zip";
        public const string INVOICE_MAIL_FIELD = "invoice_mail";
        public const string ADDRESS_TEXT_FIELD = "address_text";
        public const string MODIFY_USER_FIELD = "modify_user";
        public const string MODIFY_DATE_FIELD = "modify_date";

        public const int COMPANY_NAME_LENGTH = 50;
        public const int STREET_LENGTH = 150;
        public const int CITY_LENGTH = 50;
        public const int ZIP_LENGTH = 15;
        public const int INVOICE_MAIL_LENGTH = 150;
        public const int ADDRESS_TEXT_LENGTH = 350;
        #endregion
    }
    #endregion

    #region Suppliergroup
    public class SuppliergroupData {

        #region Constants
        public const string TABLE_NAME = "SUPPLIERGROUP";
        public const string ID_FIELD = "id";
        public const string NAME_FIELD = "name";
        public const string LOAD_ALL_SUPPLIERS_FIELD = "load_all_suppliers";

        public const int NAME_LENGTH = 50;
        #endregion
    }
    #endregion

    #region Centre
    public class CentreData {

        #region Constants
        public const string TABLE_NAME = "CENTRE";
        public const string ID_FIELD = "id";
        public const string COMPANY_ID_FIELD = "company_id";
        public const string NAME_FIELD = "name";
        public const string REMARK_FIELD = "remark";
        public const string EXPORT_PRICE_TO_ORDER_FIELD = "export_price_to_order";
        public const string MULTI_ORDERER_FIELD = "multi_orderer";
        public const string OTHER_ORDERER_CAN_TAKEOVER_FIELD = "other_orderer_can_takeover";
        public const string IS_APPROVED_BY_REQUESTOR_FIELD = "is_approved_by_requestor";
        public const string MANAGER_ID_FIELD = "manager_id";
        public const string ADDRESS_ID_FIELD = "address_id";
        public const string ACTIVE_FIELD = "active";
        public const string MODIFY_USER_FIELD = "modify_user";
        public const string MODIFY_DATE_FIELD = "modify_date";

        public const int NAME_LENGTH = 50;
        public const int REMARK_LENGTH = 50;
        #endregion
    }
    #endregion

    #region AssetcentregroupCurrency
    public class AssetcentregroupCurrencyData {

        #region Constants
        public const string TABLE_NAME = "ASSETCENTREGROUP_CURRENCY";
        public const string ASSET_CENTRE_GROUP_ID_FIELD = "asset_centre_group_id";
        public const string CURRENCY_ID_FIELD = "currency_id";

        #endregion
    }
    #endregion

    #region RequestEventOrderer
    public class RequestEventOrdererData {

        #region Constants
        public const string TABLE_NAME = "REQUEST_EVENT_ORDERER";
        public const string REQUEST_EVENT_ID_FIELD = "request_event_id";
        public const string REQUEST_EVENT_VERSION_FIELD = "request_event_version";
        public const string ORDERER_ID_FIELD = "orderer_id";
        public const string SUBSTITUTED_USER_ID_FIELD = "substituted_user_id";
        public const string IS_LAST_VERSION_FIELD = "is_last_version";

        #endregion
    }
    #endregion

    #region BusinesstripcentergroupCurrency
    public class BusinesstripcentergroupCurrencyData {

        #region Constants
        public const string TABLE_NAME = "BUSINESSTRIPCENTERGROUP_CURRENCY";
        public const string BT_CENTER_GROUP_ID_FIELD = "bt_center_group_id";
        public const string CURRENCY_ID_FIELD = "currency_id";

        #endregion
    }
    #endregion

    #region SupplierRequestorExportPrice
    public class SupplierRequestorExportPriceData {

        #region Constants
        public const string TABLE_NAME = "SUPPLIER_REQUESTOR_EXPORT_PRICE";
        public const string SUPPLIER_ID_FIELD = "supplier_id";
        public const string REQUESTOR_ID_FIELD = "requestor_id";
        public const string EXPORT_PRICE_TO_ORDER_FIELD = "export_price_to_order";

        #endregion
    }
    #endregion

    #region ParticipantSubstitute
    public class ParticipantSubstituteData {

        #region Constants
        public const string TABLE_NAME = "PARTICIPANT_SUBSTITUTE";
        public const string ID_FIELD = "id";
        public const string SUBSTITUTED_USER_ID_FIELD = "substituted_user_id";
        public const string SUBSTITUTE_USER_ID_FIELD = "substitute_user_id";
        public const string SUBSTITUTE_START_DATE_FIELD = "substitute_start_date";
        public const string SUBSTITUTE_END_DATE_FIELD = "substitute_end_date";
        public const string APPROVAL_STATUS_FIELD = "approval_status";
        public const string IS_ALLOW_TAKE_OVER_FIELD = "is_allow_take_over";
        public const string COMPANIES_IDS_FIELD = "companies_ids";
        public const string AUTHOR_ID_FIELD = "author_id";
        public const string APP_MAN_ID_FIELD = "app_man_id";
        public const string MODIFIED_USER_FIELD = "modified_user";
        public const string MODIFIED_DATE_FIELD = "modified_date";
        public const string ACTIVE_FIELD = "active";

        public const int COMPANIES_IDS_LENGTH = 150;
        #endregion
    }
    #endregion

    #region Currency
    public class CurrencyData {

        #region Constants
        public const string TABLE_NAME = "CURRENCY";
        public const string ID_FIELD = "id";
        public const string CURRENCY_NAME_FIELD = "currency_name";
        public const string CURRENCY_CODE_FIELD = "currency_code";
        public const string ACTIVE_FIELD = "active";

        public const int CURRENCY_NAME_LENGTH = 50;
        public const int CURRENCY_CODE_LENGTH = 5;
        #endregion
    }
    #endregion

    #region Readonlyaccess
    public class ReadonlyaccessData {

        #region Constants
        public const string TABLE_NAME = "READONLYACCESS";
        public const string PARTICIPANT_ID_FIELD = "participant_id";
        public const string PURCHASE_GROUP_ID_FIELD = "purchase_group_id";

        #endregion
    }
    #endregion

    #region PurchaseGroupLocal
    public class PurchaseGroupLocalData {

        #region Constants
        public const string TABLE_NAME = "PURCHASE_GROUP_LOCAL";
        public const string PURCHASE_GROUP_ID_FIELD = "purchase_group_id";
        public const string CULTURE_FIELD = "culture";
        public const string LOCAL_TEXT_FIELD = "local_text";

        public const int CULTURE_LENGTH = 50;
        public const int LOCAL_TEXT_LENGTH = 250;
        #endregion
    }
    #endregion

    #region CentreCentregroup
    public class CentreCentregroupData {

        #region Constants
        public const string TABLE_NAME = "CENTRE_CENTREGROUP";
        public const string CENTRE_GROUP_ID_FIELD = "centre_group_id";
        public const string CENTRE_ID_FIELD = "centre_id";

        #endregion
    }
    #endregion

    #region RequestEventArchive
    public class RequestEventArchiveData {

        #region Constants
        public const string TABLE_NAME = "REQUEST_EVENT_ARCHIVE";
        public const string ID_FIELD = "id";
        public const string VERSION_FIELD = "version";
        public const string REQUEST_NR_FIELD = "request_nr";
        public const string REQUESTOR_FIELD = "requestor";
        public const string MANAGER1_FIELD = "manager1";
        public const string MANAGER2_FIELD = "manager2";
        public const string MANAGER3_FIELD = "manager3";
        public const string MANAGER4_FIELD = "manager4";
        public const string MANAGER5_FIELD = "manager5";
        public const string ISSUED_FIELD = "issued";
        public const string REQUEST_TEXT_FIELD = "request_text";
        public const string LEAD_TIME_FIELD = "lead_time";
        public const string ESTIMATED_PRICE_FIELD = "estimated_price";
        public const string SUPPLIER_FIELD = "supplier";
        public const string REMARKS_FIELD = "remarks";
        public const string PURCH_MAT_INCLUDED_FIELD = "purch_mat_included";
        public const string APPROVED_1_FIELD = "approved_1";
        public const string APPROVED_2_FIELD = "approved_2";
        public const string APPROVED_3_FIELD = "approved_3";
        public const string APPROVED_4_FIELD = "approved_4";
        public const string APPROVED_5_FIELD = "approved_5";
        public const string ORDERED_FIELD = "ordered";
        public const string DELIVERED_FIELD = "delivered";
        public const string REQUEST_STATUS_FIELD = "request_status";
        public const string CURRENCY_ID_FIELD = "currency_id";
        public const string CENTRE_GROUP_ID_FIELD = "centre_group_id";
        public const string COUNTRY_ID_FIELD = "country_id";
        public const string SUPPLIER_ID_FIELD = "supplier_id";
        public const string USE_SUPPLIER_LIST_FIELD = "use_supplier_list";
        public const string MANAGER1REMARK_FIELD = "manager1Remark";
        public const string MANAGER2REMARK_FIELD = "manager2Remark";
        public const string MANAGER3REMARK_FIELD = "manager3Remark";
        public const string MANAGER4REMARK_FIELD = "manager4Remark";
        public const string MANAGER5REMARK_FIELD = "manager5Remark";
        public const string ORDERER_REMARK_FIELD = "orderer_remark";
        public const string ORDERER_ID_FIELD = "orderer_id";
        public const string SEND_BACK_REASON_FIELD = "send_back_reason";
        public const string PURCHASE_GROUP_ID_FIELD = "purchase_group_id";
        public const string ACTUAL_PRICE_FIELD = "actual_price";
        public const string ACTULA_DELIVERY_DATE_FIELD = "actula_delivery_date";
        public const string INVOICE_NUMBER_FIELD = "invoice_number";
        public const string ACT_CURRENCY_ID_FIELD = "act_currency_id";
        public const string EXCHANGE_RATE_FIELD = "exchange_rate";
        public const string SHIP_TO_ADDRESS_COMPANY_NAME_FIELD = "ship_to_address_company_name";
        public const string SHIP_TO_ADDRESS_STREET_FIELD = "ship_to_address_street";
        public const string SHIP_TO_ADDRESS_CITY_FIELD = "ship_to_address_city";
        public const string SHIP_TO_ADDRESS_ZIP_FIELD = "ship_to_address_zip";
        public const string ORDER_FILE_NAME_FIELD = "order_file_name";
        public const string REQUEST_CENTRE_ID_FIELD = "request_centre_id";
        public const string EXPORT_PRICE_TO_ORDER_FIELD = "export_price_to_order";
        public const string PROFYLAX_NR_FIELD = "profylax_nr";
        public const string YEAR_ORDER_FIELD = "year_order";
        public const string CONTRACT_NR_FIELD = "contract_nr";
        public const string UNIT_NR_FIELD = "unit_nr";
        public const string JOB_NR_FIELD = "job_nr";
        public const string COMMENTATOR_ID_FIELD = "commentator_id";
        public const string COMMENT_FIELD = "comment";
        public const string LAST_EVENT_FIELD = "last_event";
        public const string TEMPORARY_REQUEST_FIELD = "temporary_request";
        public const string MODIFY_USER_FIELD = "modify_user";
        public const string MODIFY_DATE_FIELD = "modify_date";
        public const string INTEGRATION_CODE_FIELD = "integration_code";
        public const string NOT_ORDERED_NOTIFY_DATE_FIELD = "not_ordered_notify_date";
        public const string IS_MANAGER1_INSPECTOR_FIELD = "is_manager1_inspector";
        public const string IS_MANAGER2_INSPECTOR_FIELD = "is_manager2_inspector";
        public const string IS_MANAGER3_INSPECTOR_FIELD = "is_manager3_inspector";
        public const string IS_MANAGER4_INSPECTOR_FIELD = "is_manager4_inspector";
        public const string IS_MANAGER5_INSPECTOR_FIELD = "is_manager5_inspector";

        public const int REQUEST_NR_LENGTH = 50;
        public const int INVOICE_NUMBER_LENGTH = 50;
        public const int SHIP_TO_ADDRESS_COMPANY_NAME_LENGTH = 50;
        public const int SHIP_TO_ADDRESS_STREET_LENGTH = 150;
        public const int SHIP_TO_ADDRESS_CITY_LENGTH = 50;
        public const int SHIP_TO_ADDRESS_ZIP_LENGTH = 20;
        public const int ORDER_FILE_NAME_LENGTH = 50;
        public const int PROFYLAX_NR_LENGTH = 50;
        public const int CONTRACT_NR_LENGTH = 50;
        public const int UNIT_NR_LENGTH = 50;
        public const int JOB_NR_LENGTH = 50;
        public const int INTEGRATION_CODE_LENGTH = 10;
        #endregion
    }
    #endregion

    #region TerritoryArea
    public class TerritoryAreaData {

        #region Constants
        public const string TABLE_NAME = "TERRITORY_AREA";
        public const string ID_FIELD = "id";
        public const string AREA_NAME_FIELD = "area_name";

        public const int AREA_NAME_LENGTH = 50;
        #endregion
    }
    #endregion

    #region Company
    public class CompanyData {

        #region Constants
        public const string TABLE_NAME = "COMPANY";
        public const string ID_FIELD = "id";
        public const string COUNTRY_CODE_FIELD = "country_code";
        public const string CULTURE_INFO_FIELD = "culture_info";
        public const string COMPANY_ID_FIELD = "company_id";
        public const string COMPANY_VAT_ID_FIELD = "company_vat_id";
        public const string COUNTRY_ID_FIELD = "country_id";
        public const string ACTIVE_DIRECTORY_ROOT_FIELD = "active_directory_root";
        public const string SUPPLIER_GROUP_ID_FIELD = "supplier_group_id";
        public const string IS_EVENT_LOG_ENABLED_FIELD = "is_event_log_enabled";
        public const string LAST_SUPPLIER_UPLOAD_FIELD = "last_supplier_upload";
        public const string SUPPLIER_SOURCE_FIELD = "supplier_source";
        public const string IS_SUPPLIER_MAINTENANCE_ALLOWED_FIELD = "is_supplier_maintenance_allowed";
        public const string DEFAULT_CURRENCY_ID_FIELD = "default_currency_id";
        public const string ACTIVE_FIELD = "active";

        public const int COUNTRY_CODE_LENGTH = 100;
        public const int CULTURE_INFO_LENGTH = 50;
        public const int COMPANY_ID_LENGTH = 50;
        public const int COMPANY_VAT_ID_LENGTH = 50;
        public const int ACTIVE_DIRECTORY_ROOT_LENGTH = 150;
        public const int SUPPLIER_SOURCE_LENGTH = 500;
        #endregion
    }
    #endregion

    #region Catalog
    public class CatalogData {

        #region Constants
        public const string TABLE_NAME = "CATALOG";
        public const string ID_FIELD = "id";
        public const string PARENT_ID_FIELD = "parent_id";
        public const string CATALOG_NR_FIELD = "catalog_nr";
        public const string ITEM_NAME_FIELD = "item_name";
        public const string ITEM_DESCRIPT_FIELD = "item_descript";
        public const string PRICE_FIELD = "price";
        public const string CURRENCY_FIELD = "currency";
        public const string ACTIVE_FIELD = "active";

        public const int CATALOG_NR_LENGTH = 20;
        public const int ITEM_NAME_LENGTH = 150;
        #endregion
    }
    #endregion

    #region CentreGroup
    public class CentreGroupData {

        #region Constants
        public const string TABLE_NAME = "CENTRE_GROUP";
        public const string ID_FIELD = "id";
        public const string NAME_FIELD = "name";
        public const string CURRENCY_ID_FIELD = "currency_id";
        public const string COMPANY_ID_FIELD = "company_id";
        public const string ORDER_FILE_NAME_FIELD = "order_file_name";
        public const string ORDERER_IN_ORDER_FIELD = "orderer_in_order";
        public const string MULTI_INVOICE_FIELD = "multi_invoice";
        public const string ALLOW_FREE_SUPPLIER_FIELD = "allow_free_supplier";
        public const string ALLOW_ORDERER_HAND_OVER_FIELD = "allow_orderer_hand_over";
        public const string ALLOW_YEAR_ORDER_FIELD = "allow_year_order";
        public const string ALLOW_CONTRACT_NR_FIELD = "allow_contract_nr";
        public const string ALLOW_REQUESTOR_TO_ORDER_FIELD = "allow_requestor_to_order";
        public const string ALLOW_UNIT_NR_FIELD = "allow_unit_nr";
        public const string ALLOW_JOB_NR_FIELD = "allow_job_nr";
        public const string ALLOW_INTEGRATION_CODE_FIELD = "allow_integration_code";
        public const string ALLOW_NOT_ORDERED_NOTIFICATION_FIELD = "allow_not_ordered_notification";
        public const string ALLOW_CAR_NR_FIELD = "allow_car_nr";
        public const string ALLOW_OUT_OF_EU_FIELD = "allow_out_of_eu";
        public const string ACTIVE_FIELD = "active";

        public const int NAME_LENGTH = 50;
        public const int ORDER_FILE_NAME_LENGTH = 50;
        #endregion
    }
    #endregion

    #region SubstitutionRemark
    public class SubstitutionRemarkData {

        #region Constants
        public const string TABLE_NAME = "SUBSTITUTION_REMARK";
        public const string SUBSTITUTION_ID_FIELD = "substitution_id";
        public const string REMARK_TEXT_ID_FIELD = "remark_text_id";
        public const string MODIF_DATE_FIELD = "modif_date";

        #endregion
    }
    #endregion

    #region CatalogItemImage
    public class CatalogItemImageData {

        #region Constants
        public const string TABLE_NAME = "CATALOG_ITEM_IMAGE";
        public const string ID_FIELD = "id";
        public const string CATALOG_ITEM_ID_FIELD = "catalog_item_id";
        public const string CATALOG_IMAGE_FIELD = "catalog_image";
        public const string FILE_NAME_FIELD = "file_name";

        public const int FILE_NAME_LENGTH = 150;
        #endregion
    }
    #endregion

    #region AssetRequestEvent
    public class AssetRequestEventData {

        #region Constants
        public const string TABLE_NAME = "ASSET_REQUEST_EVENT";
        public const string ID_FIELD = "id";
        public const string VERSION_FIELD = "version";
        public const string ASSET_REQUEST_TYPE_FIELD = "asset_request_type";
        public const string REQUEST_NR_FIELD = "request_nr";
        public const string REQUESTOR_ID_FIELD = "requestor_id";
        public const string ISSUED_FIELD = "issued";
        public const string ASSET_CENTRE_GROUP_ID_FIELD = "asset_centre_group_id";
        public const string REQUEST_CENTRE_ID_FIELD = "request_centre_id";
        public const string ASSET_NAME_FIELD = "asset_name";
        public const string INVERTORY_NR_FIELD = "invertory_nr";
        public const string PURCHASE_PRICE_FIELD = "purchase_price";
        public const string REQUESTOR_COMMENT_FIELD = "requestor_comment";
        public const string PROFYLAX_NR_FIELD = "profylax_nr";
        public const string PURCHASE_PRICE_CURRENCY_ID_FIELD = "purchase_price_currency_id";
        public const string DEPRICATED_PRICE_FIELD = "depricated_price";
        public const string DEPRICATED_PRICE_CURRENCY_ID_FIELD = "depricated_price_currency_id";
        public const string FM_MANAGER_ID_FIELD = "fm_manager_id";
        public const string FM_COMMENT_FIELD = "fm_comment";
        public const string YEAR_PURCHASING_FIELD = "year_purchasing";
        public const string YEAR_PRODUCTION_FIELD = "year_production";
        public const string PROPOSAL_PRICE_FIELD = "proposal_price";
        public const string PROPOSAL_PRICE_CURRENCY_ID_FIELD = "proposal_price_currency_id";
        public const string DISPOSAL_REASON_FIELD = "disposal_reason";
        public const string CENTRE_MANAGER_ID_FIELD = "centre_manager_id";
        public const string MANAGER1_ID_FIELD = "manager1_id";
        public const string MANAGER2_ID_FIELD = "manager2_id";
        public const string MANAGER3_ID_FIELD = "manager3_id";
        public const string MANAGER4_ID_FIELD = "manager4_id";
        public const string MANAGER5_ID_FIELD = "manager5_id";
        public const string APPROVED_CENTRE_MAN_FIELD = "approved_centre_man";
        public const string APPROVED_1_FIELD = "approved_1";
        public const string APPROVED_2_FIELD = "approved_2";
        public const string APPROVED_3_FIELD = "approved_3";
        public const string APPROVED_4_FIELD = "approved_4";
        public const string APPROVED_5_FIELD = "approved_5";
        public const string REQUEST_STATUS_FIELD = "request_status";
        public const string CC_MANAGER_REMARK_FIELD = "cc_manager_remark";
        public const string FM_REMARK_FIELD = "fm_remark";
        public const string APPMAN1_REMARK_FIELD = "appman1_remark";
        public const string APPMAN2_REMARK_FIELD = "appman2_remark";
        public const string APPMAN3_REMARK_FIELD = "appman3_remark";
        public const string APPMAN4_REMARK_FIELD = "appman4_remark";
        public const string APPMAN5_REMARK_FIELD = "appman5_remark";
        public const string DISPOSED_FIELD = "disposed";
        public const string DISPOSED_FROM_EVIDENCE_FIELD = "disposed_from_evidence";
        public const string FINANC_MAN_ID_FIELD = "financ_man_id";
        public const string FINANC_MAN_REMARK_FIELD = "financ_man_remark";
        public const string DISPOSED_FINANCIALLY_FIELD = "disposed_financially";
        public const string LAST_EVENT_FIELD = "last_event";
        public const string MODIFY_USER_FIELD = "modify_user";
        public const string MODIFY_DATE_FIELD = "modify_date";

        public const int REQUEST_NR_LENGTH = 50;
        public const int ASSET_NAME_LENGTH = 500;
        public const int INVERTORY_NR_LENGTH = 50;
        public const int PROFYLAX_NR_LENGTH = 50;
        #endregion
    }
    #endregion

    #region BusinesstripRequest
    public class BusinesstripRequestData {

        #region Constants
        public const string TABLE_NAME = "BUSINESSTRIP_REQUEST";
        public const string REQUEST_ID_FIELD = "request_id";
        public const string REQUEST_VERSION_FIELD = "request_version";
        public const string HEADER_ID_FIELD = "header_id";
        public const string HEADER_VERSION_FIELD = "header_version";
        public const string CURRENCY_ID_FIELD = "currency_id";
        public const string BUDGET_SUM_FIELD = "budget_sum";
        public const string BUDGET_CAR_IN_HOME_CURRENCY_FIELD = "budget_car_in_home_currency";
        public const string BUDGET_TRAIN_IN_HOME_CURRENCY_FIELD = "budget_train_in_home_currency";
        public const string BUDGET_AIRPLANE_IN_HOME_CURRENCY_FIELD = "budget_airplane_in_home_currency";
        public const string AUTHOR_ID_FIELD = "author_id";
        public const string APPROVE_MAN_1_FIELD = "approve_man_1";
        public const string APPROVE_MAN_2_FIELD = "approve_man_2";
        public const string APPROVE_MAN_3_FIELD = "approve_man_3";
        public const string APPROVE_MAN_4_FIELD = "approve_man_4";
        public const string PRIVATE_CAR_MANAGER_ID_FIELD = "private_car_manager_id";
        public const string APPROVED_1_FIELD = "approved_1";
        public const string APPROVED_2_FIELD = "approved_2";
        public const string APPROVED_3_FIELD = "approved_3";
        public const string APPROVED_4_FIELD = "approved_4";
        public const string APPROVED_CENTRE_MAN_FIELD = "approved_centre_man";
        public const string PRIVATE_CAR_APPROVED_FIELD = "private_car_approved";
        public const string APPROVE_MAN_1_REMARK_FIELD = "approve_man_1_remark";
        public const string APPROVE_MAN_2_REMARK_FIELD = "approve_man_2_remark";
        public const string APPROVE_MAN_3_REMARK_FIELD = "approve_man_3_remark";
        public const string APPROVE_MAN_4_REMARK_FIELD = "approve_man_4_remark";
        public const string APPROVE_MAN_PRIVATE_CAR_REMARK_FIELD = "approve_man_private_car_remark";
        public const string PETTY_CASH_DESK_MAN_REMARK_FIELD = "petty_cash_desk_man_remark";
        public const string IS_CUSTOM_APPROVAL_FIELD = "is_custom_approval";
        public const string FLY_TO_DEPARTURE_COUNTRY_ID_FIELD = "fly_to_departure_country_id";
        public const string FLY_TO_ARRIVAL_COUNTRY_ID_FIELD = "fly_to_arrival_country_id";
        public const string FLY_BACK_DEPARTURE_COUNTRY_ID_FIELD = "fly_back_departure_country_id";
        public const string FLY_BACK_ARRIVAL_COUNTRY_ID_FIELD = "fly_back_arrival_country_id";
        public const string FLY_TO_DEPARTURE_AIRPORT_NAME_FIELD = "fly_to_departure_airport_name";
        public const string FLY_TO_ARRIVAL_AIRPORT_NAME_FIELD = "fly_to_arrival_airport_name";
        public const string FLY_BACK_DEPARTURE_AIRPORT_NAME_FIELD = "fly_back_departure_airport_name";
        public const string FLY_BACK_ARRIVAL_AIRPORT_NAME_FIELD = "fly_back_arrival_airport_name";
        public const string FLY_TO_DEPARTURE_DATE_FIELD = "fly_to_departure_date";
        public const string FLY_TO_ARRIVAL_DATE_FIELD = "fly_to_arrival_date";
        public const string FLY_BACK_DEPARTURE_DATE_FIELD = "fly_back_departure_date";
        public const string FLY_BACK_ARRIVAL_DATE_FIELD = "fly_back_arrival_date";
        public const string COMPANY_CAR_START_PLACE_FIELD = "company_car_start_place";
        public const string IS_DEPOSITE_REQUIRED_FIELD = "is_deposite_required";
        public const string IS_DEPOSITE_MATCH_BUDGET_FIELD = "is_deposite_match_budget";
        public const string DEPOSITE_PAY_DATE_FIELD = "deposite_pay_date";
        public const string DEPOSITE_PAID_DATE_FIELD = "deposite_paid_date";
        public const string CASHDESK_MAN_ID_FIELD = "cashdesk_man_id";
        public const string CASHDESK_MAN_REMARK_FIELD = "cashdesk_man_remark";
        public const string REQUESTOR_REMARK_FIELD = "requestor_remark";
        public const string REQUEST_STATUS_FIELD = "request_status";
        public const string IS_VALID_FIELD = "is_valid";
        public const string IS_GROUP_REQUEST_FIELD = "is_group_request";
        public const string ISSUE_DATE_FIELD = "issue_date";
        public const string LAST_VERSION_FIELD = "last_version";
        public const string MODIF_USER_FIELD = "modif_user";
        public const string MODIF_DATE_FIELD = "modif_date";

        public const int FLY_TO_DEPARTURE_AIRPORT_NAME_LENGTH = 150;
        public const int FLY_TO_ARRIVAL_AIRPORT_NAME_LENGTH = 150;
        public const int FLY_BACK_DEPARTURE_AIRPORT_NAME_LENGTH = 150;
        public const int FLY_BACK_ARRIVAL_AIRPORT_NAME_LENGTH = 150;
        #endregion
    }
    #endregion

    #region CatalogLocal
    public class CatalogLocalData {

        #region Constants
        public const string TABLE_NAME = "CATALOG_LOCAL";
        public const string CATALOG_ITEM_ID_FIELD = "catalog_item_id";
        public const string CULTURE_FIELD = "culture";
        public const string LOC_ITEM_NAME_FIELD = "loc_item_name";
        public const string LOC_ITEM_DESCRIPT_FIELD = "loc_item_descript";

        public const int CULTURE_LENGTH = 10;
        public const int LOC_ITEM_NAME_LENGTH = 50;
        #endregion
    }
    #endregion

    #region BusinesstripRequestAttachment
    public class BusinesstripRequestAttachmentData {

        #region Constants
        public const string TABLE_NAME = "BUSINESSTRIP_REQUEST_ATTACHMENT";
        public const string REQUEST_ID_FIELD = "request_id";
        public const string REQUEST_VERSION_FIELD = "request_version";
        public const string ATT_ID_FIELD = "att_id";

        #endregion
    }
    #endregion

    #region CatalogProperty
    public class CatalogPropertyData {

        #region Constants
        public const string TABLE_NAME = "CATALOG_PROPERTY";
        public const string ID_FIELD = "id";
        public const string CATALOG_ITEM_ID_FIELD = "catalog_item_id";
        public const string UNIT_ID_FIELD = "unit_id";

        #endregion
    }
    #endregion

    #region CatalogPropertyValue
    public class CatalogPropertyValueData {

        #region Constants
        public const string TABLE_NAME = "CATALOG_PROPERTY_VALUE";
        public const string PROPERTY_ID_FIELD = "property_id";
        public const string PROPERTY_VALUE_FIELD = "property_value";
        public const string PROPERTY_ORDER_FIELD = "property_order";

        public const int PROPERTY_VALUE_LENGTH = 50;
        #endregion
    }
    #endregion

    #region TestFail
    public class TestFailData {

        #region Constants
        public const string TABLE_NAME = "TEST_FAIL";
        public const string ID_FIELD = "id";
        public const string TEST_NAME_FIELD = "test_name";
        public const string ERROR_MSG_FIELD = "error_msg";
        public const string FAIL_DATE_FIELD = "fail_date";

        public const int TEST_NAME_LENGTH = 500;
        public const int ERROR_MSG_LENGTH = 0;
        #endregion
    }
    #endregion

    #region ParticipantroleCentreassetgroup
    public class ParticipantroleCentreassetgroupData {

        #region Constants
        public const string TABLE_NAME = "PARTICIPANTROLE_CENTREASSETGROUP";
        public const string PARTICIPANT_ID_FIELD = "participant_id";
        public const string ASSET_CENTRE_GROUP_ID_FIELD = "asset_centre_group_id";
        public const string ROLE_ID_FIELD = "role_id";

        #endregion
    }
    #endregion

    #region CentreAssetcentregroup
    public class CentreAssetcentregroupData {

        #region Constants
        public const string TABLE_NAME = "CENTRE_ASSETCENTREGROUP";
        public const string ASSET_CENTRE_GROUP_ID_FIELD = "asset_centre_group_id";
        public const string CENTRE_ID_FIELD = "centre_id";

        #endregion
    }
    #endregion

    #region PurchasegroupImplicitrequestor
    public class PurchasegroupImplicitrequestorData {

        #region Constants
        public const string TABLE_NAME = "PURCHASEGROUP_IMPLICITREQUESTOR";
        public const string PURCHASE_CATEGORY_ID_FIELD = "purchase_category_id";
        public const string REQUESTOR_ID_FIELD = "requestor_id";
        public const string REQUESTOR_ALLOWED_FOR_OTHER_GROUP_FIELD = "requestor_allowed_for_other_group";

        #endregion
    }
    #endregion

    #region BusinesstripcentergroupReason
    public class BusinesstripcentergroupReasonData {

        #region Constants
        public const string TABLE_NAME = "BUSINESSTRIPCENTERGROUP_REASON";
        public const string BT_CENTER_GROUP_ID_FIELD = "bt_center_group_id";
        public const string REASON_ID_FIELD = "reason_id";

        #endregion
    }
    #endregion

    #region UnitMeasurementLocal
    public class UnitMeasurementLocalData {

        #region Constants
        public const string TABLE_NAME = "UNIT_MEASUREMENT_LOCAL";
        public const string UNIT_ID_FIELD = "unit_id";
        public const string CULTURE_FIELD = "culture";
        public const string LOCAL_NAME_FIELD = "local_name";

        public const int CULTURE_LENGTH = 50;
        public const int LOCAL_NAME_LENGTH = 50;
        #endregion
    }
    #endregion

    #region ParticipantroleCompany
    public class ParticipantroleCompanyData {

        #region Constants
        public const string TABLE_NAME = "PARTICIPANTROLE_COMPANY";
        public const string PARTICIPANT_ID_FIELD = "participant_id";
        public const string COMPANY_ID_FIELD = "company_id";
        public const string ROLE_ID_FIELD = "role_id";

        #endregion
    }
    #endregion

    #region UnitValueType
    public class UnitValueTypeData {

        #region Constants
        public const string TABLE_NAME = "UNIT_VALUE_TYPE";
        public const string ID_FIELD = "id";
        public const string DESCRIPTION_FIELD = "description";

        public const int DESCRIPTION_LENGTH = 50;
        #endregion
    }
    #endregion

    #region CentreBusinesstripcentregroup
    public class CentreBusinesstripcentregroupData {

        #region Constants
        public const string TABLE_NAME = "CENTRE_BUSINESSTRIPCENTREGROUP";
        public const string BUSINESS_CENTRE_GROUP_ID_FIELD = "business_centre_group_id";
        public const string CENTRE_ID_FIELD = "centre_id";

        #endregion
    }
    #endregion

    #region ParentPurchaseGroup
    public class ParentPurchaseGroupData {

        #region Constants
        public const string TABLE_NAME = "PARENT_PURCHASE_GROUP";
        public const string ID_FIELD = "id";
        public const string NAME_FIELD = "name";
        public const string ICON_NAME_FIELD = "icon_name";
        public const string COMPANY_GROUP_ID_FIELD = "company_group_id";

        public const int NAME_LENGTH = 150;
        public const int ICON_NAME_LENGTH = 50;
        #endregion
    }
    #endregion

    #region SubstituteDiscussion
    public class SubstituteDiscussionData {

        #region Constants
        public const string TABLE_NAME = "SUBSTITUTE_DISCUSSION";
        public const string SUBSTITUTE_ID_FIELD = "substitute_id";
        public const string DISCUSSION_ID_FIELD = "discussion_id";

        #endregion
    }
    #endregion

    #region Invoice
    public class InvoiceData {

        #region Constants
        public const string TABLE_NAME = "INVOICE";
        public const string ID_FIELD = "id";
        public const string REQUEST_ID_FIELD = "request_id";
        public const string REQUEST_VERSION_FIELD = "request_version";
        public const string INVOICE_NR_FIELD = "invoice_nr";
        public const string AMOUNT_FIELD = "amount";
        public const string INVOICE_DATE_FIELD = "invoice_date";

        public const int INVOICE_NR_LENGTH = 50;
        #endregion
    }
    #endregion

    #region PurchaseGroup
    public class PurchaseGroupData {

        #region Constants
        public const string TABLE_NAME = "PURCHASE_GROUP";
        public const string ID_FIELD = "id";
        public const string GROUP_NAME_FIELD = "group_name";
        public const string PROFYLAX_PURCHASE_GROUP_FIELD = "profylax_purchase_group";
        public const string SELF_ORDERED_FIELD = "self_ordered";
        public const string COMMENTATOR_ID_FIELD = "commentator_id";
        public const string PURCHASE_TYPE_FIELD = "purchase_type";
        public const string IS_APPROVAL_NEEDED_FIELD = "is_approval_needed";
        public const string IS_ORDER_NEEDED_FIELD = "is_order_needed";
        public const string IS_MULTI_ORDERER_FIELD = "is_multi_orderer";
        public const string ACTIVE_FIELD = "active";

        public const int GROUP_NAME_LENGTH = 250;
        #endregion
    }
    #endregion

    #region BusinesstripLimit
    public class BusinesstripLimitData {

        #region Constants
        public const string TABLE_NAME = "BUSINESSTRIP_LIMIT";
        public const string LIMIT_ID_FIELD = "limit_id";
        public const string BT_CENTRE_GROUP_ID_FIELD = "bt_centre_group_id";
        public const string TERRITORY_AREA_ID_FIELD = "territory_area_id";
        public const string COUNTRY_ID_FIELD = "country_id";
        public const string BT_PURPOSE_ID_FIELD = "bt_purpose_id";
        public const string LIMIT_BOTTOM_FIELD = "limit_bottom";
        public const string LIMIT_TOP_FIELD = "limit_top";
        public const string CURRENCY_ID_FIELD = "currency_id";
        public const string ACTIVE_FIELD = "active";

        #endregion
    }
    #endregion

    #region RequestNotification
    public class RequestNotificationData {

        #region Constants
        public const string TABLE_NAME = "REQUEST_NOTIFICATION";
        public const string REQUEST_ID_FIELD = "request_id";
        public const string REQUEST_VERSION_FIELD = "request_version";
        public const string SEND_DATE_FIELD = "send_date";

        #endregion
    }
    #endregion

    #region BusinesstripAttachment
    public class BusinesstripAttachmentData {

        #region Constants
        public const string TABLE_NAME = "BUSINESSTRIP_ATTACHMENT";
        public const string ID_FIELD = "id";
        public const string FILE_NAME_FIELD = "file_name";
        public const string FILE_CONTENT_FIELD = "file_content";
        public const string ATT_TYPE_FIELD = "att_type";
        public const string MODIFY_DATE_FIELD = "modify_date";
        public const string MODIFY_USER_FIELD = "modify_user";

        public const int FILE_NAME_LENGTH = 500;
        #endregion
    }
    #endregion

    #region OrdererSupplier
    public class OrdererSupplierData {

        #region Constants
        public const string TABLE_NAME = "ORDERER_SUPPLIER";
        public const string CENTRE_GROUP_ID_FIELD = "centre_group_id";
        public const string SUPPLIER_ID_FIELD = "supplier_id";
        public const string ORDERER_ID_FIELD = "orderer_id";
        public const string ORDERER_ALLOWED_FOR_OTHER_GROUP_FIELD = "orderer_allowed_for_other_group";

        #endregion
    }
    #endregion

    #region Privacy
    public class PrivacyData {

        #region Constants
        public const string TABLE_NAME = "PRIVACY";
        public const string ID_FIELD = "id";
        public const string NAME_FIELD = "name";

        public const int NAME_LENGTH = 50;
        #endregion
    }
    #endregion

    #region RequestDiscussion
    public class RequestDiscussionData {

        #region Constants
        public const string TABLE_NAME = "REQUEST_DISCUSSION";
        public const string REQUEST_ID_FIELD = "request_id";
        public const string REQUEST_VERSION_FIELD = "request_version";
        public const string DISCUSSION_ID_FIELD = "discussion_id";

        #endregion
    }
    #endregion

    #region BusinesstripReason
    public class BusinesstripReasonData {

        #region Constants
        public const string TABLE_NAME = "BUSINESSTRIP_REASON";
        public const string ID_FIELD = "id";
        public const string NAME_FIELD = "name";
        public const string ACTIVE_FIELD = "active";

        public const int NAME_LENGTH = 50;
        #endregion
    }
    #endregion

    #region PurchasegroupExcludeorderer
    public class PurchasegroupExcludeordererData {

        #region Constants
        public const string TABLE_NAME = "PURCHASEGROUP_EXCLUDEORDERER";
        public const string PURCHASE_CATEGORY_ID_FIELD = "purchase_category_id";
        public const string ORDERER_ID_FIELD = "orderer_id";

        #endregion
    }
    #endregion

    #region PurchasegroupExcluderequestor
    public class PurchasegroupExcluderequestorData {

        #region Constants
        public const string TABLE_NAME = "PURCHASEGROUP_EXCLUDEREQUESTOR";
        public const string PURCHASE_CATEGORY_ID_FIELD = "purchase_category_id";
        public const string REQUESTOR_ID_FIELD = "requestor_id";

        #endregion
    }
    #endregion

    #region BusinesstripGroup
    public class BusinesstripGroupData {

        #region Constants
        public const string TABLE_NAME = "BUSINESSTRIP_GROUP";
        public const string GROUP_ID_FIELD = "group_id";
        public const string REQUEST_ID_FIELD = "request_id";
        public const string REQUEST_VERSION_FIELD = "request_version";
        public const string IS_ACTIVE_FIELD = "is_active";

        #endregion
    }
    #endregion

    #region TestIndicator
    public class TestIndicatorData {

        #region Constants
        public const string TABLE_NAME = "TEST_INDICATOR";
        public const string ID_FIELD = "id";
        public const string TEST_TEXT_FIELD = "test_text";

        public const int TEST_TEXT_LENGTH = 500;
        #endregion
    }
    #endregion

    #region RequestorCentre
    public class RequestorCentreData {

        #region Constants
        public const string TABLE_NAME = "REQUESTOR_CENTRE";
        public const string PARTICIPANT_ID_FIELD = "participant_id";
        public const string CENTRE_ID_FIELD = "centre_id";

        #endregion
    }
    #endregion

    #region ParticipantRole
    public class ParticipantRoleData {

        #region Constants
        public const string TABLE_NAME = "PARTICIPANT_ROLE";
        public const string ID_FIELD = "id";
        public const string NAME_FIELD = "name";

        public const int NAME_LENGTH = 50;
        #endregion
    }
    #endregion

    #region BusinesstripManagerRole
    public class BusinesstripManagerRoleData {

        #region Constants
        public const string TABLE_NAME = "BUSINESSTRIP_MANAGER_ROLE";
        public const string BT_CENTRE_GROUP_ID_FIELD = "bt_centre_group_id";
        public const string BT_LIMIT_ID_FIELD = "bt_limit_id";
        public const string APPROVE_LEVEL_ID_FIELD = "approve_level_id";
        public const string PARTICIPANT_ID_FIELD = "participant_id";
        public const string ACTIVE_FIELD = "active";

        #endregion
    }
    #endregion

    #region RequestOrder
    public class RequestOrderData {

        #region Constants
        public const string TABLE_NAME = "REQUEST_ORDER";
        public const string ID_FIELD = "id";
        public const string REQUEST_ID_FIELD = "request_id";
        public const string REQUEST_VERSION_FIELD = "request_version";
        public const string OTIS_COMPANY_ADDRESS_FIELD = "otis_company_address";
        public const string REQUESTOR_ADDRESS_FIELD = "requestor_address";
        public const string ORDERER_NAME_FIELD = "orderer_name";
        public const string ORDERER_MAIL_FIELD = "orderer_mail";
        public const string ORDERER_PHONE_FIELD = "orderer_phone";
        public const string ORDERER_FAX_FIELD = "orderer_fax";
        public const string SUPPLIER_ADDRESS_FIELD = "supplier_address";
        public const string REQUEST_TEXT_FIELD = "request_text";
        public const string EST_PRICE_FIELD = "est_price";
        public const string CURRENCY_ID_FIELD = "currency_id";
        public const string DELIV_DATE_FIELD = "deliv_date";
        public const string CONTRACT_NR_FIELD = "contract_nr";
        public const string IS_PRICE_EXPORTED_FIELD = "is_price_exported";
        public const string MAIL_ADDRESSES_FIELD = "mail_addresses";
        public const string ATTACHMENT_IDS_FIELD = "attachment_ids";
        public const string CULTURE_NAME_FIELD = "culture_name";
        public const string SUPPLIER_CONTACT_NAME_FIELD = "supplier_contact_name";
        public const string SUPPLIER_MAIL_FIELD = "supplier_mail";
        public const string SUPPLIER_PHONE_FIELD = "supplier_phone";
        public const string SUPPLIER_FAX_FIELD = "supplier_fax";
        public const string MODIFY_USER_FIELD = "modify_user";
        public const string MODIFY_DATE_FIELD = "modify_date";

        public const int OTIS_COMPANY_ADDRESS_LENGTH = 500;
        public const int REQUESTOR_ADDRESS_LENGTH = 500;
        public const int ORDERER_NAME_LENGTH = 50;
        public const int ORDERER_MAIL_LENGTH = 50;
        public const int ORDERER_PHONE_LENGTH = 50;
        public const int ORDERER_FAX_LENGTH = 50;
        public const int SUPPLIER_ADDRESS_LENGTH = 500;
        public const int CONTRACT_NR_LENGTH = 50;
        public const int MAIL_ADDRESSES_LENGTH = 500;
        public const int ATTACHMENT_IDS_LENGTH = 150;
        public const int CULTURE_NAME_LENGTH = 10;
        public const int SUPPLIER_CONTACT_NAME_LENGTH = 50;
        public const int SUPPLIER_MAIL_LENGTH = 50;
        public const int SUPPLIER_PHONE_LENGTH = 50;
        public const int SUPPLIER_FAX_LENGTH = 50;
        #endregion
    }
    #endregion

    #region ParentPurchasePurchaseGroup
    public class ParentPurchasePurchaseGroupData {

        #region Constants
        public const string TABLE_NAME = "PARENT_PURCHASE_PURCHASE_GROUP";
        public const string PARENT_PURCHASE_GROUP_ID_FIELD = "parent_purchase_group_id";
        public const string PURCHASE_GROUP_ID_FIELD = "purchase_group_id";

        #endregion
    }
    #endregion

    #region PurchaseGroupSupplier
    public class PurchaseGroupSupplierData {

        #region Constants
        public const string TABLE_NAME = "PURCHASE_GROUP_SUPPLIER";
        public const string PURCHASE_GROUP_ID_FIELD = "purchase_group_id";
        public const string DEFAULT_SUPPLIER_ID_FIELD = "default_supplier_id";

        #endregion
    }
    #endregion

    #region ParticipantroleBusinesstripcentregroup
    public class ParticipantroleBusinesstripcentregroupData {

        #region Constants
        public const string TABLE_NAME = "PARTICIPANTROLE_BUSINESSTRIPCENTREGROUP";
        public const string PARTICIPANT_ID_FIELD = "participant_id";
        public const string BT_CENTRE_GROUP_ID_FIELD = "bt_centre_group_id";
        public const string ROLE_ID_FIELD = "role_id";

        #endregion
    }
    #endregion

    #region Datatype
    public class DatatypeData {

        #region Constants
        public const string TABLE_NAME = "DATATYPE";
        public const string ID_FIELD = "id";
        public const string FIELD_TYPE_FIELD = "field_type";

        public const int FIELD_TYPE_LENGTH = 50;
        #endregion
    }
    #endregion

    #region RequestField
    public class RequestFieldData {

        #region Constants
        public const string TABLE_NAME = "REQUEST_FIELD";
        public const string ID_FIELD = "id";
        public const string FIELD_NAME_FIELD = "field_name";
        public const string IS_MANDATORY_FIELD = "is_mandatory";
        public const string DATA_TYPE_ID_FIELD = "data_type_id";

        public const int FIELD_NAME_LENGTH = 50;
        #endregion
    }
    #endregion

    #region BusinesstripHeader
    public class BusinesstripHeaderData {

        #region Constants
        public const string TABLE_NAME = "BUSINESSTRIP_HEADER";
        public const string ID_FIELD = "id";
        public const string VERSION_FIELD = "version";
        public const string BT_NR_FIELD = "bt_nr";
        public const string REQUESTOR_ID_FIELD = "requestor_id";
        public const string REQUESTOR_COST_CENTRE_ID_FIELD = "requestor_cost_centre_id";
        public const string REINVOICE_COST_CENTRE_ID_FIELD = "reinvoice_cost_centre_id";
        public const string DESTINATION_FIELD = "destination";
        public const string PURPOSE_FIELD = "purpose";
        public const string PURPOSE_TYPE_ID_FIELD = "purpose_type_id";
        public const string START_DATE_FIELD = "start_date";
        public const string END_DATE_FIELD = "end_date";
        public const string ORIG_END_DATE_FIELD = "orig_end_date";
        public const string COMPANY_ID_FIELD = "company_id";
        public const string COUNTRY_ID_FIELD = "country_id";
        public const string BT_CENTRE_GROUP_ID_FIELD = "bt_centre_group_id";
        public const string TRANSPORT_TYPE_FIELD = "transport_type";
        public const string REQUESTOR_HOME_CURRENCY_ID_FIELD = "requestor_home_currency_id";
        public const string HEADER_STATUS_FIELD = "header_status";
        public const string LAST_VERSION_FIELD = "last_version";
        public const string MODIF_USER_FIELD = "modif_user";
        public const string MODIF_DATE_FIELD = "modif_date";

        public const int BT_NR_LENGTH = 20;
        public const int DESTINATION_LENGTH = 150;
        public const int PURPOSE_LENGTH = 500;
        public const int TRANSPORT_TYPE_LENGTH = 50;
        #endregion
    }
    #endregion

    #region UserSetting
    public class UserSettingData {

        #region Constants
        public const string TABLE_NAME = "USER_SETTING";
        public const string USER_ID_FIELD = "user_id";
        public const string DEFAULT_LANG_FIELD = "default_lang";
        public const string ONLY_MY_REQUEST_AS_DEFAULT_FIELD = "only_my_request_as_default";
        public const string FILTER_SETTINGS_FIELD = "filter_settings";
        public const string JOB_POSITION_FIELD = "job_position";
        public const string IS_COMMODITY_ICON_FIELD = "is_commodity_icon";

        public const int DEFAULT_LANG_LENGTH = 10;
        public const int JOB_POSITION_LENGTH = 50;
        #endregion
    }
    #endregion

    #region RequestEventApproval
    public class RequestEventApprovalData {

        #region Constants
        public const string TABLE_NAME = "REQUEST_EVENT_APPROVAL";
        public const string REQUEST_EVENT_ID_FIELD = "request_event_id";
        public const string REQUEST_EVENT_VERSION_FIELD = "request_event_version";
        public const string APP_MAN_ID_FIELD = "app_man_id";
        public const string APP_LEVEL_ID_FIELD = "app_level_id";
        public const string APPROVE_STATUS_FIELD = "approve_status";
        public const string SUBSTITUTED_USER_ID_FIELD = "substituted_user_id";
        public const string IS_LAST_VERSION_FIELD = "is_last_version";

        #endregion
    }
    #endregion

    #region BusinesstripLastset
    public class BusinesstripLastsetData {

        #region Constants
        public const string TABLE_NAME = "BUSINESSTRIP_LASTSET";
        public const string REQUESTOR_ID_FIELD = "requestor_id";
        public const string APP_MAN_1_ID_FIELD = "app_man_1_id";
        public const string APP_MAN_2_ID_FIELD = "app_man_2_id";
        public const string APP_MAN_3_ID_FIELD = "app_man_3_id";
        public const string COST_CENTRE_ID_FIELD = "cost_centre_id";

        #endregion
    }
    #endregion

    #region ParentPurchaseGroupLocal
    public class ParentPurchaseGroupLocalData {

        #region Constants
        public const string TABLE_NAME = "PARENT_PURCHASE_GROUP_LOCAL";
        public const string PARENT_PURCHASE_GROUP_ID_FIELD = "parent_purchase_group_id";
        public const string CULTURE_FIELD = "culture";
        public const string LOCAL_TEXT_FIELD = "local_text";

        public const int CULTURE_LENGTH = 10;
        public const int LOCAL_TEXT_LENGTH = 500;
        #endregion
    }
    #endregion

    #region EventAttachement
    public class EventAttachementData {

        #region Constants
        public const string TABLE_NAME = "EVENT_ATTACHEMENT";
        public const string REQUEST_EVENT_ID_FIELD = "request_event_id";
        public const string REQUEST_VERSION_FIELD = "request_version";
        public const string ATT_ID_FIELD = "att_id";
        public const string IS_LAST_VERSION_FIELD = "is_last_version";

        #endregion
    }
    #endregion

    #region AssetEventAttachment
    public class AssetEventAttachmentData {

        #region Constants
        public const string TABLE_NAME = "ASSET_EVENT_ATTACHMENT";
        public const string REQUEST_EVENT_ID_FIELD = "request_event_id";
        public const string REQUEST_VERSION_FIELD = "request_version";
        public const string ATT_ID_FIELD = "att_id";

        #endregion
    }
    #endregion

    #region CompanyGroup
    public class CompanyGroupData {

        #region Constants
        public const string TABLE_NAME = "COMPANY_GROUP";
        public const string ID_FIELD = "id";
        public const string NAME_FIELD = "name";

        public const int NAME_LENGTH = 50;
        #endregion
    }
    #endregion

    #region CentregroupPurchasegroup
    public class CentregroupPurchasegroupData {

        #region Constants
        public const string TABLE_NAME = "CENTREGROUP_PURCHASEGROUP";
        public const string CENTRE_GROUP_ID_FIELD = "centre_group_id";
        public const string PURCHASE_GROUP_ID_FIELD = "purchase_group_id";

        #endregion
    }
    #endregion

    #region Supplier
    public class SupplierData {

        #region Constants
        public const string TABLE_NAME = "SUPPLIER";
        public const string ID_FIELD = "id";
        public const string SUPP_NAME_FIELD = "supp_name";
        public const string SUPPLIER_GROUP_ID_FIELD = "supplier_group_id";
        public const string SUPPLIER_SEARCH_KEY_FIELD = "supplier_search_key";
        public const string SUPPLIER_LOCAL_APP_ID_FIELD = "supplier_local_app_id";
        public const string SUPPLIER_ID_FIELD = "supplier_id";
        public const string DIC_FIELD = "dic";
        public const string COUNTRY_FIELD = "country";
        public const string VAT_FIELD = "vat";
        public const string CONTACT_PERSON_FIELD = "contact_person";
        public const string PHONE_FIELD = "phone";
        public const string MOBILE_PHONE_FIELD = "mobile_phone";
        public const string FAX_FIELD = "fax";
        public const string STREET_PART1_FIELD = "street_part1";
        public const string STREET_PART2_FIELD = "street_part2";
        public const string CITY_FIELD = "city";
        public const string ZIP_FIELD = "zip";
        public const string EMAIL_FIELD = "email";
        public const string CREDITOR_GROUP_FIELD = "creditor_group";
        public const string BANK_ACCOUNT_FIELD = "bank_account";
        public const string LANG_FIELD = "lang";
        public const string EMAIL_USED_FIELD = "email_used";
        public const string ACTIVE_FIELD = "active";

        public const int SUPP_NAME_LENGTH = 400;
        public const int SUPPLIER_SEARCH_KEY_LENGTH = 500;
        public const int SUPPLIER_LOCAL_APP_ID_LENGTH = 50;
        public const int SUPPLIER_ID_LENGTH = 50;
        public const int DIC_LENGTH = 50;
        public const int COUNTRY_LENGTH = 100;
        public const int CONTACT_PERSON_LENGTH = 400;
        public const int PHONE_LENGTH = 50;
        public const int MOBILE_PHONE_LENGTH = 50;
        public const int FAX_LENGTH = 50;
        public const int STREET_PART1_LENGTH = 150;
        public const int STREET_PART2_LENGTH = 150;
        public const int CITY_LENGTH = 150;
        public const int ZIP_LENGTH = 25;
        public const int EMAIL_LENGTH = 150;
        public const int BANK_ACCOUNT_LENGTH = 50;
        public const int LANG_LENGTH = 20;
        public const int EMAIL_USED_LENGTH = 150;
        #endregion
    }
    #endregion

    #region MaintenanceEvent
    public class MaintenanceEventData {

        #region Constants
        public const string TABLE_NAME = "MAINTENANCE_EVENT";
        public const string ID_FIELD = "id";
        public const string COMPANY_ID_FIELD = "company_id";
        public const string COMPANY_NAME_FIELD = "company_name";
        public const string CENTRE_GROUP_ID_FIELD = "centre_group_id";
        public const string CENTRE_GROUP_NAME_FIELD = "centre_group_name";
        public const string CENTRE_ID_FIELD = "centre_id";
        public const string CENTRE_NAME_FIELD = "centre_name";
        public const string PURCHASE_GROUP_ID_FIELD = "purchase_group_id";
        public const string PURCHASE_GROUP_NAME_FIELD = "purchase_group_name";
        public const string USER_ID_FIELD = "user_id";
        public const string USER_NAME_FIELD = "user_name";
        public const string MSG_CODE_FIELD = "msg_code";
        public const string MSG_TEXT_FIELD = "msg_text";
        public const string IS_SUBJECT_DELETED_FIELD = "is_subject_deleted";
        public const string MODIF_USER_FIELD = "modif_user";
        public const string MODIF_DATE_FIELD = "modif_date";

        public const int COMPANY_NAME_LENGTH = 50;
        public const int CENTRE_GROUP_NAME_LENGTH = 50;
        public const int CENTRE_NAME_LENGTH = 50;
        public const int PURCHASE_GROUP_NAME_LENGTH = 50;
        public const int USER_NAME_LENGTH = 50;
        public const int MSG_TEXT_LENGTH = 500;
        #endregion
    }
    #endregion

    #region PurchasegroupImplicitorderer
    public class PurchasegroupImplicitordererData {

        #region Constants
        public const string TABLE_NAME = "PURCHASEGROUP_IMPLICITORDERER";
        public const string PURCHASE_CATEGORY_ID_FIELD = "purchase_category_id";
        public const string ORDERER_ID_FIELD = "orderer_id";
        public const string ORDERER_ALLOWED_FOR_OTHER_GROUP_FIELD = "orderer_allowed_for_other_group";
        public const string IS_DEFAULT_ORDERER_FIELD = "is_default_orderer";

        #endregion
    }
    #endregion

    #region FilterValue
    public class FilterValueData {

        #region Constants
        public const string TABLE_NAME = "FILTER_VALUE";
        public const string ID_FIELD = "id";
        public const string FILED_TYPE_FIELD = "filed_type";
        public const string COUNTRY_ID_FIELD = "country_id";
        public const string ITEM_ID_FIELD = "item_id";
        public const string ITEM_TEXT_FIELD = "item_text";

        public const int ITEM_TEXT_LENGTH = 250;
        #endregion
    }
    #endregion

    #region Attachement
    public class AttachementData {

        #region Constants
        public const string TABLE_NAME = "ATTACHEMENT";
        public const string ID_FIELD = "id";
        public const string FILE_NAME_FIELD = "file_name";
        public const string FILE_CONTENT_FIELD = "file_content";
        public const string ORDERER_ATTACHMENT_FIELD = "orderer_attachment";
        public const string MODIFY_DATE_FIELD = "modify_date";
        public const string MODIFY_USER_FIELD = "modify_user";
        public const string ATT_TYPE_FIELD = "att_type";
        public const string SIZE_KB_FIELD = "size_kb";

        public const int FILE_NAME_LENGTH = 500;
        #endregion
    }
    #endregion

    #region RequestEventExpand
    public class RequestEventExpandData {

        #region Constants
        public const string TABLE_NAME = "REQUEST_EVENT_EXPAND";
        public const string REQUEST_ID_FIELD = "request_id";
        public const string REQUEST_VERSION_FIELD = "request_version";
        public const string LAST_APPROVAL_DATE_FIELD = "last_approval_date";
        public const string ORDERERD_DATE_FIELD = "ordererd_date";
        public const string LAST_EVENT_FIELD = "last_event";

        #endregion
    }
    #endregion

    #region AssetRequestType
    public class AssetRequestTypeData {

        #region Constants
        public const string TABLE_NAME = "ASSET_REQUEST_TYPE";
        public const string REQUEST_TYPE_ID_FIELD = "request_type_id";
        public const string NAME_FIELD = "name";

        public const int NAME_LENGTH = 50;
        #endregion
    }
    #endregion

    #region CentregroupCurrency
    public class CentregroupCurrencyData {

        #region Constants
        public const string TABLE_NAME = "CENTREGROUP_CURRENCY";
        public const string CENTRE_GROUP_ID_FIELD = "centre_group_id";
        public const string CURRENCY_ID_FIELD = "currency_id";

        #endregion
    }
    #endregion

    #region AssetManagerRole
    public class AssetManagerRoleData {

        #region Constants
        public const string TABLE_NAME = "ASSET_MANAGER_ROLE";
        public const string ASSET_CENTRE_GROUP_ID_FIELD = "asset_centre_group_id";
        public const string ASSET_REQUEST_TYPE_ID_FIELD = "asset_request_type_id";
        public const string APP_LEVEL_ID_FIELD = "app_level_id";
        public const string MANAGER_ID_FIELD = "manager_id";
        public const string ACTIVE_FIELD = "active";

        #endregion
    }
    #endregion

}
