//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kamsyk.Reget.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Address()
        {
            this.Centre = new HashSet<Centre>();
            this.Ship_To_Address = new HashSet<Ship_To_Address>();
            this.Request_Event = new HashSet<Request_Event>();
        }
    
        public int id { get; set; }
        public string company_name { get; set; }
        public int company_id { get; set; }
        public string street { get; set; }
        public string city { get; set; }
        public string zip { get; set; }
        public string invoice_mail { get; set; }
        public int modify_user { get; set; }
        public System.DateTime modify_date { get; set; }
        public string address_text { get; set; }
        public bool is_active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Centre> Centre { get; set; }
        public virtual Company Company { get; set; }
        public virtual Participants Participants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ship_To_Address> Ship_To_Address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request_Event> Request_Event { get; set; }
    }
}
