//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kamsyk.Reget.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset_Request_Event
    {
        public int id { get; set; }
        public int version { get; set; }
        public Nullable<int> asset_request_type { get; set; }
        public string request_nr { get; set; }
        public int requestor_id { get; set; }
        public System.DateTime issued { get; set; }
        public Nullable<int> asset_centre_group_id { get; set; }
        public Nullable<int> request_centre_id { get; set; }
        public string asset_name { get; set; }
        public string invertory_nr { get; set; }
        public Nullable<decimal> purchase_price { get; set; }
        public string requestor_comment { get; set; }
        public string profylax_nr { get; set; }
        public Nullable<int> purchase_price_currency_id { get; set; }
        public Nullable<decimal> depricated_price { get; set; }
        public Nullable<int> depricated_price_currency_id { get; set; }
        public Nullable<int> fm_manager_id { get; set; }
        public string fm_comment { get; set; }
        public Nullable<int> year_purchasing { get; set; }
        public Nullable<int> year_production { get; set; }
        public Nullable<decimal> proposal_price { get; set; }
        public Nullable<int> proposal_price_currency_id { get; set; }
        public Nullable<int> disposal_reason { get; set; }
        public Nullable<int> centre_manager_id { get; set; }
        public Nullable<int> manager1_id { get; set; }
        public Nullable<int> manager2_id { get; set; }
        public Nullable<int> manager3_id { get; set; }
        public Nullable<int> manager4_id { get; set; }
        public Nullable<int> manager5_id { get; set; }
        public Nullable<int> approved_centre_man { get; set; }
        public Nullable<int> approved_1 { get; set; }
        public Nullable<int> approved_2 { get; set; }
        public Nullable<int> approved_3 { get; set; }
        public Nullable<int> approved_4 { get; set; }
        public Nullable<int> approved_5 { get; set; }
        public Nullable<int> request_status { get; set; }
        public string cc_manager_remark { get; set; }
        public string fm_remark { get; set; }
        public string appman1_remark { get; set; }
        public string appman2_remark { get; set; }
        public string appman3_remark { get; set; }
        public string appman4_remark { get; set; }
        public string appman5_remark { get; set; }
        public Nullable<bool> disposed { get; set; }
        public Nullable<bool> disposed_from_evidence { get; set; }
        public Nullable<int> financ_man_id { get; set; }
        public string financ_man_remark { get; set; }
        public Nullable<bool> disposed_financially { get; set; }
        public bool last_event { get; set; }
        public int modify_user { get; set; }
        public System.DateTime modify_date { get; set; }
    
        public virtual Asset_Centre_Group Asset_Centre_Group { get; set; }
        public virtual Participants Participants { get; set; }
        public virtual Asset_Request_Type Asset_Request_Type1 { get; set; }
        public virtual Centre Centre { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual Currency Currency1 { get; set; }
        public virtual Currency Currency2 { get; set; }
        public virtual Participants Participants1 { get; set; }
        public virtual Participants Participants2 { get; set; }
        public virtual Participants Participants3 { get; set; }
        public virtual Participants Participants4 { get; set; }
        public virtual Participants Participants5 { get; set; }
        public virtual Participants Participants6 { get; set; }
        public virtual Participants Participants7 { get; set; }
    }
}
