//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kamsyk.Reget.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Centre_Group
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Centre_Group()
        {
            this.Manager_Role = new HashSet<Manager_Role>();
            this.Orderer_Supplier = new HashSet<Orderer_Supplier>();
            this.ParticipantRole_CentreGroup = new HashSet<ParticipantRole_CentreGroup>();
            this.Request_Event = new HashSet<Request_Event>();
            this.Ship_To_Address = new HashSet<Ship_To_Address>();
            this.Centre = new HashSet<Centre>();
            this.Foreign_Currency = new HashSet<Currency>();
            this.Purchase_Group = new HashSet<Purchase_Group>();
            this.Maintenance_Event = new HashSet<Maintenance_Event>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int currency_id { get; set; }
        public int company_id { get; set; }
        public string order_file_name { get; set; }
        public Nullable<bool> orderer_in_order { get; set; }
        public Nullable<bool> multi_invoice { get; set; }
        public Nullable<bool> allow_free_supplier { get; set; }
        public Nullable<bool> allow_orderer_hand_over { get; set; }
        public Nullable<bool> allow_year_order { get; set; }
        public Nullable<bool> allow_contract_nr { get; set; }
        public Nullable<bool> allow_requestor_to_order { get; set; }
        public Nullable<bool> allow_unit_nr { get; set; }
        public Nullable<bool> allow_job_nr { get; set; }
        public Nullable<bool> allow_integration_code { get; set; }
        public Nullable<bool> allow_not_ordered_notification { get; set; }
        public Nullable<bool> allow_car_nr { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<bool> allow_out_of_eu { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Currency Currency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Manager_Role> Manager_Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orderer_Supplier> Orderer_Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParticipantRole_CentreGroup> ParticipantRole_CentreGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request_Event> Request_Event { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ship_To_Address> Ship_To_Address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Centre> Centre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Currency> Foreign_Currency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchase_Group> Purchase_Group { get; set; }
        public virtual SupplierGroup SupplierGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Maintenance_Event> Maintenance_Event { get; set; }
    }
}
