//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kamsyk.Reget.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.Centre_Group = new HashSet<Centre_Group>();
            this.Filter_Value = new HashSet<Filter_Value>();
            this.Participant_Office_Role = new HashSet<Participant_Office_Role>();
            this.Participants = new HashSet<Participants>();
            this.Participants1 = new HashSet<Participants>();
            this.Request_Event = new HashSet<Request_Event>();
            this.Centre = new HashSet<Centre>();
            this.Address = new HashSet<Address>();
            this.Maintenance_Event = new HashSet<Maintenance_Event>();
            this.Parent_Purchase_Group = new HashSet<Parent_Purchase_Group>();
            this.Currency = new HashSet<Currency>();
            this.Custom_Field = new HashSet<Custom_Field>();
            this.App_Text_Store = new HashSet<App_Text_Store>();
        }
    
        public int id { get; set; }
        public string country_code { get; set; }
        public string culture_info { get; set; }
        public string company_id { get; set; }
        public string company_vat_id { get; set; }
        public int country_id { get; set; }
        public string active_directory_root { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<int> supplier_group_id { get; set; }
        public Nullable<bool> is_event_log_enabled { get; set; }
        public Nullable<System.DateTime> last_supplier_upload { get; set; }
        public Nullable<bool> is_supplier_maintenance_allowed { get; set; }
        public string supplier_source { get; set; }
        public int default_currency_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Centre_Group> Centre_Group { get; set; }
        public virtual Country Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Filter_Value> Filter_Value { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Participant_Office_Role> Participant_Office_Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Participants> Participants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Participants> Participants1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request_Event> Request_Event { get; set; }
        public virtual SupplierGroup SupplierGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Centre> Centre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Address> Address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Maintenance_Event> Maintenance_Event { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parent_Purchase_Group> Parent_Purchase_Group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Currency> Currency { get; set; }
        public virtual Currency Currency1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Custom_Field> Custom_Field { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<App_Text_Store> App_Text_Store { get; set; }
    }
}
