//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kamsyk.Reget.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Custom_Field
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Custom_Field()
        {
            this.PurchaseGroup_CustomField = new HashSet<PurchaseGroup_CustomField>();
            this.RequestEvent_CustomFieldValue = new HashSet<RequestEvent_CustomFieldValue>();
            this.Company = new HashSet<Company>();
            this.CustomField_Local = new HashSet<CustomField_Local>();
        }
    
        public int id { get; set; }
        public string label { get; set; }
        public bool is_mandatory { get; set; }
        public int date_type_id { get; set; }
        public bool is_active { get; set; }
    
        public virtual DataType DataType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseGroup_CustomField> PurchaseGroup_CustomField { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestEvent_CustomFieldValue> RequestEvent_CustomFieldValue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Company> Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomField_Local> CustomField_Local { get; set; }
    }
}
