//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kamsyk.Reget.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discussion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Discussion()
        {
            this.Request_Discussion = new HashSet<Request_Discussion>();
            this.Substitute_Discussion = new HashSet<Substitute_Discussion>();
        }
    
        public int id { get; set; }
        public int author_id { get; set; }
        public Nullable<int> app_text_store_id { get; set; }
        public System.DateTime modif_date { get; set; }
    
        public virtual App_Text_Store App_Text_Store { get; set; }
        public virtual Participants Participants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request_Discussion> Request_Discussion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Substitute_Discussion> Substitute_Discussion { get; set; }
    }
}
