//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kamsyk.Reget.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event_Attachement
    {
        public int request_event_id { get; set; }
        public int request_version { get; set; }
        public int att_id { get; set; }
        public Nullable<bool> is_last_version { get; set; }
    
        public virtual Attachement Attachement { get; set; }
        public virtual Request_Event Request_Event { get; set; }
    }
}
