//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kamsyk.Reget.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filter_Value
    {
        public int id { get; set; }
        public int filed_type { get; set; }
        public Nullable<int> country_id { get; set; }
        public Nullable<int> item_id { get; set; }
        public string item_text { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
