//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kamsyk.Reget.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maintenance_Event
    {
        public int id { get; set; }
        public Nullable<int> centre_group_id { get; set; }
        public Nullable<int> centre_id { get; set; }
        public Nullable<int> purchase_group_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public int msg_code { get; set; }
        public string msg_text { get; set; }
        public int modif_user { get; set; }
        public System.DateTime modif_date { get; set; }
        public Nullable<int> company_id { get; set; }
        public Nullable<bool> is_subject_deleted { get; set; }
        public string company_name { get; set; }
        public string centre_group_name { get; set; }
        public string centre_name { get; set; }
        public string purchase_group_name { get; set; }
        public string user_name { get; set; }
    
        public virtual Centre Centre { get; set; }
        public virtual Centre_Group Centre_Group { get; set; }
        public virtual Maintenance_Event_Code Maintenance_Event_Code { get; set; }
        public virtual Participants Participants { get; set; }
        public virtual Participants Participants1 { get; set; }
        public virtual Purchase_Group Purchase_Group { get; set; }
        public virtual Company Company { get; set; }
    }
}
