//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kamsyk.Reget.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manager_Role
    {
        public int centre_group_id { get; set; }
        public int purchase_group_limit_id { get; set; }
        public int approve_level_id { get; set; }
        public int participant_id { get; set; }
        public Nullable<bool> is_inspector { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<int> modify_user { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
    
        public virtual Approve_Level Approve_Level { get; set; }
        public virtual Centre_Group Centre_Group { get; set; }
        public virtual Purchase_Group_Limit Purchase_Group_Limit { get; set; }
        public virtual Participants Participants { get; set; }
        public virtual Participants Participants_Modif { get; set; }
    }
}
