//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kamsyk.Reget.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orderer_Supplier
    {
        public int centre_group_id { get; set; }
        public int supplier_id { get; set; }
        public int orderer_id { get; set; }
        public Nullable<bool> orderer_allowed_for_other_group { get; set; }
    
        public virtual Centre_Group Centre_Group { get; set; }
        public virtual Participants Participants { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
