//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kamsyk.Reget.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participant_Substitute
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Participant_Substitute()
        {
            this.Substitution_Remark = new HashSet<Substitution_Remark>();
            this.Substitute_Discussion = new HashSet<Substitute_Discussion>();
        }
    
        public int id { get; set; }
        public int substituted_user_id { get; set; }
        public int substitute_user_id { get; set; }
        public System.DateTime substitute_start_date { get; set; }
        public System.DateTime substitute_end_date { get; set; }
        public int modified_user { get; set; }
        public System.DateTime modified_date { get; set; }
        public Nullable<bool> active { get; set; }
        public int approval_status { get; set; }
        public Nullable<bool> is_allow_take_over { get; set; }
        public string companies_ids { get; set; }
        public int author_id { get; set; }
        public Nullable<int> app_man_id { get; set; }
    
        public virtual Participants SubstituteUser { get; set; }
        public virtual Participants SubstitutedUser { get; set; }
        public virtual Participants ModifUser { get; set; }
        public virtual Participants Author { get; set; }
        public virtual Participants AppMan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Substitution_Remark> Substitution_Remark { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Substitute_Discussion> Substitute_Discussion { get; set; }
    }
}
