//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kamsyk.Reget.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participant_Office_Role
    {
        public int participant_id { get; set; }
        public int office_id { get; set; }
        public int role_id { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Participant_Role Participant_Role { get; set; }
        public virtual Participants Participants { get; set; }
    }
}
