//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kamsyk.Reget.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participant_Role
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Participant_Role()
        {
            this.Participant_Office_Role = new HashSet<Participant_Office_Role>();
            this.ParticipantRole_BusinessTripCentreGroup = new HashSet<ParticipantRole_BusinessTripCentreGroup>();
            this.ParticipantRole_CentreAssetGroup = new HashSet<ParticipantRole_CentreAssetGroup>();
            this.ParticipantRole_CentreGroup = new HashSet<ParticipantRole_CentreGroup>();
            this.Participants = new HashSet<Participants>();
            this.PurchaseGroup_CustomField = new HashSet<PurchaseGroup_CustomField>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Participant_Office_Role> Participant_Office_Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParticipantRole_BusinessTripCentreGroup> ParticipantRole_BusinessTripCentreGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParticipantRole_CentreAssetGroup> ParticipantRole_CentreAssetGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParticipantRole_CentreGroup> ParticipantRole_CentreGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Participants> Participants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseGroup_CustomField> PurchaseGroup_CustomField { get; set; }
    }
}
