//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kamsyk.Reget.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParticipantPhoto
    {
        public int participant_id { get; set; }
        public byte[] user_picture_240 { get; set; }
        public System.DateTime modif_date { get; set; }
    
        public virtual Participants Participants { get; set; }
    }
}
