//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kamsyk.Reget.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase_Group
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Purchase_Group()
        {
            this.Purchase_Group_Limit = new HashSet<Purchase_Group_Limit>();
            this.Purchase_Group_Local = new HashSet<Purchase_Group_Local>();
            this.PurchaseGroup_ImplicitOrderer = new HashSet<PurchaseGroup_ImplicitOrderer>();
            this.PurchaseGroup_ImplicitRequestor = new HashSet<PurchaseGroup_ImplicitRequestor>();
            this.PurchaseGroup_Requestor = new HashSet<PurchaseGroup_Requestor>();
            this.Request_Event = new HashSet<Request_Event>();
            this.Centre_Group = new HashSet<Centre_Group>();
            this.Parent_Purchase_Group = new HashSet<Parent_Purchase_Group>();
            this.Supplier = new HashSet<Supplier>();
            this.ParticipantsExcludeOrderers = new HashSet<Participants>();
            this.ParticipantsExcludeRequestor = new HashSet<Participants>();
            this.PurchaseGroup_Orderer = new HashSet<Participants>();
            this.Participants4 = new HashSet<Participants>();
            this.Maintenance_Event = new HashSet<Maintenance_Event>();
            this.PurchaseGroup_CustomField = new HashSet<PurchaseGroup_CustomField>();
        }
    
        public int id { get; set; }
        public string group_name { get; set; }
        public Nullable<bool> profylax_purchase_group { get; set; }
        public Nullable<bool> self_ordered { get; set; }
        public Nullable<int> commentator_id { get; set; }
        public Nullable<bool> active { get; set; }
        public bool is_approval_needed { get; set; }
        public bool is_order_needed { get; set; }
        public int purchase_type { get; set; }
        public bool is_multi_orderer { get; set; }
    
        public virtual Participants Participants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchase_Group_Limit> Purchase_Group_Limit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchase_Group_Local> Purchase_Group_Local { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseGroup_ImplicitOrderer> PurchaseGroup_ImplicitOrderer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseGroup_ImplicitRequestor> PurchaseGroup_ImplicitRequestor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseGroup_Requestor> PurchaseGroup_Requestor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request_Event> Request_Event { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Centre_Group> Centre_Group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parent_Purchase_Group> Parent_Purchase_Group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supplier> Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Participants> ParticipantsExcludeOrderers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Participants> ParticipantsExcludeRequestor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Participants> PurchaseGroup_Orderer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Participants> Participants4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Maintenance_Event> Maintenance_Event { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseGroup_CustomField> PurchaseGroup_CustomField { get; set; }
    }
}
