//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kamsyk.Reget.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase_Group_Limit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Purchase_Group_Limit()
        {
            this.Manager_Role = new HashSet<Manager_Role>();
        }
    
        public int limit_id { get; set; }
        public int purchase_group_id { get; set; }
        public Nullable<decimal> limit_bottom { get; set; }
        public Nullable<decimal> limit_top { get; set; }
        public Nullable<decimal> skip_limit { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<int> modify_user { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public int approve_level_id { get; set; }
        public Nullable<bool> is_limit_bottom_multipl { get; set; }
        public Nullable<bool> is_limit_top_multipl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Manager_Role> Manager_Role { get; set; }
        public virtual Participants Participants { get; set; }
        public virtual Purchase_Group Purchase_Group { get; set; }
    }
}
