//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kamsyk.Reget.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InternalRequestEntities : DbContext
    {
        public InternalRequestEntities()
            : base("name=InternalRequestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Approve_Level> Approve_Level { get; set; }
        public virtual DbSet<Asset_Centre_Group> Asset_Centre_Group { get; set; }
        public virtual DbSet<Asset_Manager_Role> Asset_Manager_Role { get; set; }
        public virtual DbSet<Asset_Request_Identificator> Asset_Request_Identificator { get; set; }
        public virtual DbSet<Asset_Request_Type> Asset_Request_Type { get; set; }
        public virtual DbSet<AssetCentreGroup_Currency> AssetCentreGroup_Currency { get; set; }
        public virtual DbSet<Centre> Centre { get; set; }
        public virtual DbSet<Centre_BusinessTripCentreGroup> Centre_BusinessTripCentreGroup { get; set; }
        public virtual DbSet<Centre_Group> Centre_Group { get; set; }
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Country_Local> Country_Local { get; set; }
        public virtual DbSet<Currency> Currency { get; set; }
        public virtual DbSet<Exchange_Rate> Exchange_Rate { get; set; }
        public virtual DbSet<Filter_Value> Filter_Value { get; set; }
        public virtual DbSet<Invoice> Invoice { get; set; }
        public virtual DbSet<Manager_Role> Manager_Role { get; set; }
        public virtual DbSet<Orderer_Supplier> Orderer_Supplier { get; set; }
        public virtual DbSet<Parent_Purchase_Group> Parent_Purchase_Group { get; set; }
        public virtual DbSet<Parent_Purchase_Group_Local> Parent_Purchase_Group_Local { get; set; }
        public virtual DbSet<Participant_Office_Role> Participant_Office_Role { get; set; }
        public virtual DbSet<Participant_Role> Participant_Role { get; set; }
        public virtual DbSet<Participant_Substitute> Participant_Substitute { get; set; }
        public virtual DbSet<ParticipantRole_BusinessTripCentreGroup> ParticipantRole_BusinessTripCentreGroup { get; set; }
        public virtual DbSet<ParticipantRole_CentreAssetGroup> ParticipantRole_CentreAssetGroup { get; set; }
        public virtual DbSet<ParticipantRole_CentreGroup> ParticipantRole_CentreGroup { get; set; }
        public virtual DbSet<Participants> Participants { get; set; }
        public virtual DbSet<Purchase_Group> Purchase_Group { get; set; }
        public virtual DbSet<Purchase_Group_Limit> Purchase_Group_Limit { get; set; }
        public virtual DbSet<Purchase_Group_Local> Purchase_Group_Local { get; set; }
        public virtual DbSet<PurchaseGroup_ImplicitOrderer> PurchaseGroup_ImplicitOrderer { get; set; }
        public virtual DbSet<PurchaseGroup_ImplicitRequestor> PurchaseGroup_ImplicitRequestor { get; set; }
        public virtual DbSet<PurchaseGroup_Requestor> PurchaseGroup_Requestor { get; set; }
        public virtual DbSet<Request_Event> Request_Event { get; set; }
        public virtual DbSet<Request_Event_Archive> Request_Event_Archive { get; set; }
        public virtual DbSet<Request_Event_Expand> Request_Event_Expand { get; set; }
        public virtual DbSet<Request_Identificator> Request_Identificator { get; set; }
        public virtual DbSet<Request_Mail> Request_Mail { get; set; }
        public virtual DbSet<Request_Notification> Request_Notification { get; set; }
        public virtual DbSet<Request_Order> Request_Order { get; set; }
        public virtual DbSet<Ship_To_Address> Ship_To_Address { get; set; }
        public virtual DbSet<Supplier> Supplier { get; set; }
        public virtual DbSet<Supplier_Contact> Supplier_Contact { get; set; }
        public virtual DbSet<Supplier_Requestor_Export_Price> Supplier_Requestor_Export_Price { get; set; }
        public virtual DbSet<SupplierGroup> SupplierGroup { get; set; }
        public virtual DbSet<User_GridSetting> User_GridSetting { get; set; }
        public virtual DbSet<User_Setting> User_Setting { get; set; }
        public virtual DbSet<Address> Address { get; set; }
        public virtual DbSet<Maintenance_Event> Maintenance_Event { get; set; }
        public virtual DbSet<Maintenance_Event_Code> Maintenance_Event_Code { get; set; }
        public virtual DbSet<DataType> DataType { get; set; }
        public virtual DbSet<Request_Field> Request_Field { get; set; }
        public virtual DbSet<Test_Indicator> Test_Indicator { get; set; }
        public virtual DbSet<Company_Group> Company_Group { get; set; }
        public virtual DbSet<ParticipantPhoto> ParticipantPhoto { get; set; }
        public virtual DbSet<Test_Fail> Test_Fail { get; set; }
        public virtual DbSet<Request_Item> Request_Item { get; set; }
        public virtual DbSet<Unit_Measurement> Unit_Measurement { get; set; }
        public virtual DbSet<Unit_Measurement_Local> Unit_Measurement_Local { get; set; }
        public virtual DbSet<Unit_Value_Type> Unit_Value_Type { get; set; }
        public virtual DbSet<Asset_Request_Event> Asset_Request_Event { get; set; }
        public virtual DbSet<Privacy> Privacy { get; set; }
        public virtual DbSet<PurchaseGroup_CustomField> PurchaseGroup_CustomField { get; set; }
        public virtual DbSet<Custom_Field> Custom_Field { get; set; }
        public virtual DbSet<RequestEvent_CustomFieldValue> RequestEvent_CustomFieldValue { get; set; }
        public virtual DbSet<CustomField_Local> CustomField_Local { get; set; }
        public virtual DbSet<Attachement> Attachement { get; set; }
        public virtual DbSet<Event_Attachement> Event_Attachement { get; set; }
        public virtual DbSet<App_Text_Store> App_Text_Store { get; set; }
        public virtual DbSet<Substitution_Remark> Substitution_Remark { get; set; }
        public virtual DbSet<Request_Event_Orderer> Request_Event_Orderer { get; set; }
        public virtual DbSet<Request_AuthorizedUsers> Request_AuthorizedUsers { get; set; }
        public virtual DbSet<Request_Text> Request_Text { get; set; }
        public virtual DbSet<Discussion> Discussion { get; set; }
        public virtual DbSet<Request_Discussion> Request_Discussion { get; set; }
        public virtual DbSet<Substitute_Discussion> Substitute_Discussion { get; set; }
        public virtual DbSet<Request_AccessRequest> Request_AccessRequest { get; set; }
        public virtual DbSet<Request_Event_Approval> Request_Event_Approval { get; set; }
    }
}
