//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kamsyk.Reget.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request_Item
    {
        public int id { get; set; }
        public int request_id { get; set; }
        public int request_version { get; set; }
        public string name { get; set; }
        public decimal amount { get; set; }
        public decimal unit_price { get; set; }
        public int unit_measurement_id { get; set; }
        public bool is_last_version { get; set; }
        public int currency_id { get; set; }
    
        public virtual Request_Event Request_Event { get; set; }
        public virtual Unit_Measurement Unit_Measurement { get; set; }
        public virtual Currency Currency { get; set; }
    }
}
