//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kamsyk.Reget.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request_Event_Expand
    {
        public int request_id { get; set; }
        public int request_version { get; set; }
        public Nullable<System.DateTime> last_approval_date { get; set; }
        public Nullable<System.DateTime> ordererd_date { get; set; }
        public Nullable<bool> last_event { get; set; }
    
        public virtual Request_Event Request_Event { get; set; }
    }
}
