//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kamsyk.Reget.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request_Event_Approval
    {
        public int id { get; set; }
        public int request_event_id { get; set; }
        public int request_event_version { get; set; }
        public int app_man_id { get; set; }
        public int app_level_id { get; set; }
        public int approve_status { get; set; }
        public Nullable<int> substituted_user_id { get; set; }
        public bool is_last_version { get; set; }
        public Nullable<System.DateTime> modif_date { get; set; }
    
        public virtual Participants AppMan { get; set; }
        public virtual Participants Substitutee { get; set; }
        public virtual Request_Event Request_Event { get; set; }
    }
}
