//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kamsyk.Reget.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request_Order
    {
        public int id { get; set; }
        public int request_id { get; set; }
        public int request_version { get; set; }
        public string otis_company_address { get; set; }
        public string requestor_address { get; set; }
        public string orderer_name { get; set; }
        public string orderer_mail { get; set; }
        public string orderer_phone { get; set; }
        public string orderer_fax { get; set; }
        public string supplier_address { get; set; }
        public string request_text { get; set; }
        public Nullable<decimal> est_price { get; set; }
        public Nullable<int> currency_id { get; set; }
        public Nullable<System.DateTime> deliv_date { get; set; }
        public Nullable<bool> is_price_exported { get; set; }
        public string mail_addresses { get; set; }
        public string attachment_ids { get; set; }
        public string culture_name { get; set; }
        public int modify_user { get; set; }
        public System.DateTime modify_date { get; set; }
        public string supplier_contact_name { get; set; }
        public string supplier_mail { get; set; }
        public string supplier_phone { get; set; }
        public string supplier_fax { get; set; }
        public string contract_nr { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Participants Participants { get; set; }
        public virtual Request_Event Request_Event { get; set; }
    }
}
