//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kamsyk.Reget.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request_Discussion
    {
        public int request_id { get; set; }
        public int request_version { get; set; }
        public int discussion_id { get; set; }
        public bool is_active { get; set; }
    
        public virtual Discussion Discussion { get; set; }
        public virtual Request_Event Request_Event { get; set; }
    }
}
