//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kamsyk.Reget.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request_Identificator
    {
        public int centre_id { get; set; }
        public int reueast_year { get; set; }
        public int last_request_id { get; set; }
    
        public virtual Centre Centre { get; set; }
    }
}
