//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kamsyk.Reget.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request_Mail
    {
        public int id { get; set; }
        public int request_id { get; set; }
        public int request_version { get; set; }
        public string sender { get; set; }
        public string recipients { get; set; }
        public string order_name { get; set; }
        public byte[] order_content { get; set; }
        public string attachment_ids { get; set; }
        public string term_cond_name { get; set; }
        public byte[] term_cond_content { get; set; }
        public System.DateTime sent_date { get; set; }
    
        public virtual Request_Event Request_Event { get; set; }
    }
}
