//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kamsyk.Reget.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request_Field
    {
        public int id { get; set; }
        public string field_name { get; set; }
        public bool is_mandatory { get; set; }
        public Nullable<int> data_type_id { get; set; }
    
        public virtual DataType DataType { get; set; }
    }
}
