//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kamsyk.Reget.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request_Event_Archive
    {
        public int id { get; set; }
        public int version { get; set; }
        public string request_nr { get; set; }
        public Nullable<int> requestor { get; set; }
        public Nullable<int> manager1 { get; set; }
        public Nullable<int> manager2 { get; set; }
        public Nullable<int> manager3 { get; set; }
        public Nullable<int> manager4 { get; set; }
        public Nullable<int> manager5 { get; set; }
        public Nullable<System.DateTime> issued { get; set; }
        public string request_text { get; set; }
        public Nullable<System.DateTime> lead_time { get; set; }
        public Nullable<decimal> estimated_price { get; set; }
        public string supplier { get; set; }
        public string remarks { get; set; }
        public Nullable<bool> purch_mat_included { get; set; }
        public Nullable<int> approved_1 { get; set; }
        public Nullable<int> approved_2 { get; set; }
        public Nullable<int> approved_3 { get; set; }
        public Nullable<int> approved_4 { get; set; }
        public Nullable<int> approved_5 { get; set; }
        public Nullable<bool> ordered { get; set; }
        public Nullable<bool> delivered { get; set; }
        public Nullable<int> request_status { get; set; }
        public Nullable<int> currency_id { get; set; }
        public int centre_group_id { get; set; }
        public Nullable<int> country_id { get; set; }
        public Nullable<int> supplier_id { get; set; }
        public Nullable<bool> use_supplier_list { get; set; }
        public string manager1Remark { get; set; }
        public string manager2Remark { get; set; }
        public string manager3Remark { get; set; }
        public string manager4Remark { get; set; }
        public string manager5Remark { get; set; }
        public string orderer_remark { get; set; }
        public Nullable<int> orderer_id { get; set; }
        public string send_back_reason { get; set; }
        public Nullable<int> purchase_group_id { get; set; }
        public Nullable<decimal> actual_price { get; set; }
        public Nullable<System.DateTime> actula_delivery_date { get; set; }
        public string invoice_number { get; set; }
        public Nullable<int> act_currency_id { get; set; }
        public Nullable<decimal> exchange_rate { get; set; }
        public string ship_to_address_company_name { get; set; }
        public string ship_to_address_street { get; set; }
        public string ship_to_address_city { get; set; }
        public string ship_to_address_zip { get; set; }
        public string order_file_name { get; set; }
        public Nullable<int> request_centre_id { get; set; }
        public Nullable<bool> export_price_to_order { get; set; }
        public string profylax_nr { get; set; }
        public Nullable<bool> year_order { get; set; }
        public string contract_nr { get; set; }
        public string unit_nr { get; set; }
        public string job_nr { get; set; }
        public Nullable<int> commentator_id { get; set; }
        public string comment { get; set; }
        public Nullable<bool> last_event { get; set; }
        public Nullable<bool> temporary_request { get; set; }
        public int modify_user { get; set; }
        public System.DateTime modify_date { get; set; }
        public string integration_code { get; set; }
        public Nullable<System.DateTime> not_ordered_notify_date { get; set; }
        public Nullable<bool> is_manager1_inspector { get; set; }
        public Nullable<bool> is_manager2_inspector { get; set; }
        public Nullable<bool> is_manager3_inspector { get; set; }
        public Nullable<bool> is_manager4_inspector { get; set; }
        public Nullable<bool> is_manager5_inspector { get; set; }
    }
}
