//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kamsyk.Reget.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ship_To_Address
    {
        public int id { get; set; }
        public Nullable<int> participant_id { get; set; }
        public Nullable<int> centre_id { get; set; }
        public Nullable<int> centre_group_id { get; set; }
        public string company_name { get; set; }
        public string street { get; set; }
        public string city { get; set; }
        public string zip { get; set; }
        public string invoice_mail { get; set; }
        public Nullable<bool> active { get; set; }
        public int address_id { get; set; }
    
        public virtual Centre Centre { get; set; }
        public virtual Centre_Group Centre_Group { get; set; }
        public virtual Participants Participants { get; set; }
        public virtual Address Address { get; set; }
    }
}
