//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kamsyk.Reget.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Substitution_Remark
    {
        public int substitution_id { get; set; }
        public int remark_text_id { get; set; }
        public Nullable<System.DateTime> modif_date { get; set; }
    
        public virtual App_Text_Store App_Text_Store { get; set; }
        public virtual Participant_Substitute Participant_Substitute { get; set; }
    }
}
