//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kamsyk.Reget.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Substitute_Discussion
    {
        public int substitute_id { get; set; }
        public int discussion_id { get; set; }
        public Nullable<bool> is_active { get; set; }
    
        public virtual Discussion Discussion { get; set; }
        public virtual Participant_Substitute Participant_Substitute { get; set; }
    }
}
