//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kamsyk.Reget.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier_Contact
    {
        public int id { get; set; }
        public int supplier_id { get; set; }
        public string first_name { get; set; }
        public string surname { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public Nullable<bool> last_used { get; set; }
        public int modified_user_id { get; set; }
        public System.DateTime modified_date { get; set; }
    
        public virtual Participants Participants { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
