//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kamsyk.Reget.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier_Requestor_Export_Price
    {
        public int supplier_id { get; set; }
        public int requestor_id { get; set; }
        public Nullable<bool> export_price_to_order { get; set; }
    
        public virtual Participants Participants { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
