//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kamsyk.Reget.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supplier()
        {
            this.Orderer_Supplier = new HashSet<Orderer_Supplier>();
            this.Request_Event = new HashSet<Request_Event>();
            this.Supplier_Contact = new HashSet<Supplier_Contact>();
            this.Supplier_Requestor_Export_Price = new HashSet<Supplier_Requestor_Export_Price>();
            this.Purchase_Group = new HashSet<Purchase_Group>();
        }
    
        public int id { get; set; }
        public string supp_name { get; set; }
        public int supplier_group_id { get; set; }
        public string supplier_local_app_id { get; set; }
        public string supplier_id { get; set; }
        public string dic { get; set; }
        public string country { get; set; }
        public Nullable<bool> vat { get; set; }
        public string contact_person { get; set; }
        public string phone { get; set; }
        public string mobile_phone { get; set; }
        public string fax { get; set; }
        public string street_part1 { get; set; }
        public string street_part2 { get; set; }
        public string city { get; set; }
        public string zip { get; set; }
        public string email { get; set; }
        public Nullable<int> creditor_group { get; set; }
        public string bank_account { get; set; }
        public string lang { get; set; }
        public string email_used { get; set; }
        public Nullable<bool> active { get; set; }
        public string supplier_search_key { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orderer_Supplier> Orderer_Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request_Event> Request_Event { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supplier_Contact> Supplier_Contact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supplier_Requestor_Export_Price> Supplier_Requestor_Export_Price { get; set; }
        public virtual SupplierGroup SupplierGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchase_Group> Purchase_Group { get; set; }
    }
}
