//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kamsyk.Reget.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test_Fail
    {
        public int id { get; set; }
        public string test_name { get; set; }
        public string error_msg { get; set; }
        public System.DateTime fail_date { get; set; }
    }
}
