//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kamsyk.Reget.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Setting
    {
        public int user_id { get; set; }
        public string default_lang { get; set; }
        public Nullable<bool> only_my_request_as_default { get; set; }
        public string filter_settings { get; set; }
        public string job_position { get; set; }
        public Nullable<bool> is_commodity_icon { get; set; }
    
        public virtual Participants Participants { get; set; }
    }
}
